"""DDR RAG Companion App — the book's final payoff, in one small screen.

Ask an engineering question against the sample Daily Drilling Report
archive and see the whole idea end to end: retrieval → local-model answer
→ citations → the original evidence. Evidence first, answer second.

Run it with:
    streamlit run book/app/streamlit_app.py

The retrieval and generation are the book's own code (Chapters 4, 5, 9),
imported, not reimplemented. This file is only the screen around them.
"""

import streamlit as st

import helpers
from helpers import run_query

SAMPLE_QUESTIONS = [
    "What led to the fishing operation on report #50?",
    "What happened around the stuck pipe event?",
    "Which reports mention high torque?",
    "Which reports mention tight hole?",
    "What operational issue followed the packer setting failure?",
]


@st.cache_resource(show_spinner="Loading the embedding model (first run only)…")
def load_model():
    """Load Chapter 4's embedding model once and reuse it across queries.
    device='cpu' is pinned to match the book's documented numbers."""
    from semantic_search import MODEL_NAME
    from sentence_transformers import SentenceTransformer
    return SentenceTransformer(MODEL_NAME, device="cpu")


@st.cache_data(show_spinner="Preparing the sample archive (first run only)…")
def prepare_archive():
    """Make sure the extracted-text folder exists (rebuild it from the
    committed sample PDFs on a fresh clone). Runs once, then cached."""
    helpers.ensure_text_dir()
    return True


def render_pipeline():
    st.markdown(
        "<div style='text-align:center;padding:6px 0 2px;color:#5a5a5a;font-size:0.95rem'>"
        "📄 DDR PDFs &nbsp;→&nbsp; 📝 Text &nbsp;→&nbsp; 🔎 Retriever "
        "&nbsp;→&nbsp; 🧠 Local model &nbsp;→&nbsp; ✅ Answer + Evidence"
        "</div>",
        unsafe_allow_html=True,
    )


def render_result(result: dict):
    st.subheader("Question")
    st.write(result["query"])

    # Answer -- shown only after the evidence discipline is set up. If the
    # reader asked for generation but Ollama is down, say so plainly.
    if result["generated"]:
        st.subheader("Answer — generated by the local model")
        st.success(result["answer"])
        st.caption("Generated from the retrieved evidence below. Check it against the source reports.")
    elif result["ollama_message"]:
        st.subheader("Answer")
        st.warning(result["ollama_message"])

    st.subheader("Retrieved evidence")
    st.caption("The reports the retriever matched to your question, best first.")
    for card in result["cards"]:
        with st.container(border=True):
            st.markdown(f"**Report:** `{card['filename']}`")
            meta = f"**Score:** {card['score']:.3f}"
            if card["date"]:
                meta += f" &nbsp;·&nbsp; **Date:** {card['date']}"
            st.markdown(meta)
            st.markdown(f"**Excerpt:** “{card['snippet']}”")
            if card["why"]:
                st.caption("Why it matters — " + card["why"])

    with st.expander("Why this answer?"):
        st.markdown("The transparency panel: everything behind the answer above.")
        st.markdown("**Your question**")
        st.code(result["query"], language=None)

        st.markdown("**Retrieved reports (ranked)**")
        for card in result["cards"]:
            st.markdown(f"- `{card['filename']}` — score {card['score']:.3f}")

        st.markdown("**Evidence snippets**")
        for card in result["cards"]:
            st.markdown(f"- {card['snippet']}")

        st.markdown("**Answer source**")
        st.write(
            "Generated by the local model from the evidence above."
            if result["generated"]
            else "Retrieval only — no answer was generated."
        )

        if result["prompt"]:
            st.markdown("**Prompt sent to the local model**")
            prompt = result["prompt"]
            shown = prompt[:4000] + ("\n\n… (truncated for display)" if len(prompt) > 4000 else "")
            st.code(shown, language=None)


def render_limitations():
    st.divider()
    st.caption(
        "This app is for learning. It runs on a small public sample archive. "
        "Always verify answers against the original report before using them for "
        "engineering decisions — the engineer remains responsible for the call."
    )


def main():
    st.set_page_config(page_title="DDR RAG Companion App", page_icon="🛢️", layout="centered")
    st.title("DDR RAG Companion App")
    st.caption("Ask a question. See the evidence. Check the source.")
    render_pipeline()

    st.sidebar.header("Ask a question")
    sample = st.sidebar.selectbox("Sample question", SAMPLE_QUESTIONS)
    custom = st.sidebar.text_input("…or type your own", "")
    question = custom.strip() or sample
    top_k = st.sidebar.slider("Reports to retrieve (top-k)", 1, 10, 5)
    generate = st.sidebar.checkbox("Generate an answer with a local model", value=True)
    model_name = st.sidebar.text_input("Ollama model", helpers.DEFAULT_MODEL)
    asked = st.sidebar.button("Ask", type="primary", use_container_width=True)

    if asked:
        prepare_archive()
        model = load_model()
        spinner = "Retrieving evidence" + ("… and generating an answer" if generate else "") + "…"
        with st.spinner(spinner):
            st.session_state["result"] = run_query(
                question, model,
                top_k=top_k, generate=generate, model_name=model_name,
            )

    result = st.session_state.get("result")
    if result:
        render_result(result)
    else:
        st.info("Pick a question in the sidebar and press **Ask**.")

    render_limitations()


if __name__ == "__main__":
    main()
