<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>6&nbsp; Scanned Reports and OCR Quality Gates – Building Industrial RAG Systems from Daily Drilling Reports</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/chapter_07.html" rel="next">
<link href="../chapters/chapter_05.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-de63f62b328812d8e578a4d74e282472.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-6b6957c917596b414ec0b78690761e87.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-de63f62b328812d8e578a4d74e282472.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-e10d541d56eb9122d05640a0c0a0767f.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-04b3fb33f2a973da1159f90c12b2b682.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../site_libs/bootstrap/bootstrap-e10d541d56eb9122d05640a0c0a0767f.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-sidebar docked quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/chapter_06.html">Part II — Industrialising the System</a></li><li class="breadcrumb-item"><a href="../chapters/chapter_06.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Scanned Reports and OCR Quality Gates</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Building Industrial RAG Systems from Daily Drilling Reports</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/djimrastephane/ddr-rag-book" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <a href="../Building-Industrial-RAG-Systems-from-Daily-Drilling-Reports.pdf" title="Download PDF" class="quarto-navigation-tool px-1" aria-label="Download PDF"><i class="bi bi-file-pdf"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../acknowledgements.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Acknowledgements</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Part 0 — Preparing Your Python Workshop</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapter_00.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Part 0: Preparing Your Python Workshop</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Part I — Foundations</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapter_01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Reading Your First DDR</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapter_02.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Cleaning Operational Text</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapter_03.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Searching DDRs</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapter_04.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Semantic Search</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapter_05.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">First RAG System</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Part II — Industrialising the System</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapter_06.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Scanned Reports and OCR Quality Gates</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapter_07.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Chunking That Respects Report Structure</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapter_08.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Vector Databases at Scale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapter_09.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Hybrid Retrieval and Reranking</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapter_10.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Traceable Answers and Hallucination Mitigation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapter_11.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Evaluating Retrieval Quality</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapter_12.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Sequence Detection: Building Toward Cross-Well Intelligence</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapter_13.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Daily Ingestion: Keeping the System Live</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendix/appendix_a_environment_setup.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Appendix A: Environment Setup</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendix/appendix_a1_jupyter.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Appendix A1: Using Jupyter Notebook</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendix/appendix_a2_vscode.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Appendix A2: Using VS Code</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendix/appendix_a3_pycharm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Appendix A3: Using PyCharm Community</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendix/appendix_a4_positron.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Appendix A4: Using Positron</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendix/appendix_a5_terminal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Appendix A5: Terminal-Only Workflow</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendix/appendix_b_oilfield_glossary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Appendix B: Oilfield Abbreviation Glossary</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#learning-objectives" id="toc-learning-objectives" class="nav-link active" data-scroll-target="#learning-objectives"><span class="header-section-number">6.1</span> Learning objectives</a></li>
  <li><a href="#operational-problem" id="toc-operational-problem" class="nav-link" data-scroll-target="#operational-problem"><span class="header-section-number">6.2</span> Operational Problem</a></li>
  <li><a href="#example-ddr-extract" id="toc-example-ddr-extract" class="nav-link" data-scroll-target="#example-ddr-extract"><span class="header-section-number">6.3</span> Example DDR extract</a></li>
  <li><a href="#theory" id="toc-theory" class="nav-link" data-scroll-target="#theory"><span class="header-section-number">6.4</span> Theory</a></li>
  <li><a href="#implementation" id="toc-implementation" class="nav-link" data-scroll-target="#implementation"><span class="header-section-number">6.5</span> Implementation</a>
  <ul class="collapse">
  <li><a href="#step-1-build-a-quality-gate-function" id="toc-step-1-build-a-quality-gate-function" class="nav-link" data-scroll-target="#step-1-build-a-quality-gate-function"><span class="header-section-number">6.5.1</span> Step 1: build a quality-gate function</a></li>
  <li><a href="#step-2-see-it-on-a-real-scanned-page" id="toc-step-2-see-it-on-a-real-scanned-page" class="nav-link" data-scroll-target="#step-2-see-it-on-a-real-scanned-page"><span class="header-section-number">6.5.2</span> Step 2: see it on a real scanned page</a></li>
  </ul></li>
  <li><a href="#production-reality" id="toc-production-reality" class="nav-link" data-scroll-target="#production-reality"><span class="header-section-number">6.6</span> Production Reality</a></li>
  <li><a href="#practical-exercise" id="toc-practical-exercise" class="nav-link" data-scroll-target="#practical-exercise"><span class="header-section-number">6.7</span> Practical exercise</a></li>
  <li><a href="#field-notes" id="toc-field-notes" class="nav-link" data-scroll-target="#field-notes"><span class="header-section-number">6.8</span> Field notes</a></li>
  <li><a href="#challenge-exercise" id="toc-challenge-exercise" class="nav-link" data-scroll-target="#challenge-exercise"><span class="header-section-number">6.9</span> Challenge exercise</a></li>
  <li><a href="#key-takeaways" id="toc-key-takeaways" class="nav-link" data-scroll-target="#key-takeaways"><span class="header-section-number">6.10</span> Key takeaways</a></li>
  <li><a href="#repository-files" id="toc-repository-files" class="nav-link" data-scroll-target="#repository-files"><span class="header-section-number">6.11</span> Repository files</a></li>
  <li><a href="#what-can-you-do-now-that-you-couldnt-do-before" id="toc-what-can-you-do-now-that-you-couldnt-do-before" class="nav-link" data-scroll-target="#what-can-you-do-now-that-you-couldnt-do-before"><span class="header-section-number">6.12</span> What can you do now that you couldn’t do before?</a></li>
  <li><a href="#suggested-next-step" id="toc-suggested-next-step" class="nav-link" data-scroll-target="#suggested-next-step"><span class="header-section-number">6.13</span> Suggested next step</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/djimrastephane/ddr-rag-book/edit/main/chapters/chapter_06.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/djimrastephane/ddr-rag-book/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/chapter_06.html">Part II — Industrialising the System</a></li><li class="breadcrumb-item"><a href="../chapters/chapter_06.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Scanned Reports and OCR Quality Gates</span></a></li></ol></nav>
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title"><span id="sec-chapter-06" class="quarto-section-identifier"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Scanned Reports and OCR Quality Gates</span></span></h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="pipeline-diagram">
<p><img src="../figures/diagrams/pipeline_ch06_light.svg" class="diagram-light img-fluid" width="160"> <img src="../figures/diagrams/pipeline_ch06_dark.svg" class="diagram-dark img-fluid" width="160"></p>
</div>
<div class="chapter-status">
<p>Progress <code>██████░░░░░░░</code> <strong>6 / 13</strong> &nbsp;·&nbsp; <strong>Estimated time:</strong> 45–60 min &nbsp;·&nbsp; <strong>Difficulty:</strong> 🟠 Intermediate</p>
</div>
<section id="learning-objectives" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="learning-objectives"><span class="header-section-number">6.1</span> Learning objectives</h2>
<p>By the end of this chapter, you will be able to:</p>
<ul>
<li>Recognise when a DDR PDF has no extractable text and needs OCR.</li>
<li>Make a scanned-style page from a digital report, recover its text with OCR, and score whether that text is trustworthy enough to index.</li>
<li>Build a quality gate that rejects bad OCR output <em>before</em> it enters your search index, rather than trying to fix it after the fact.</li>
</ul>
</section>
<section id="operational-problem" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="operational-problem"><span class="header-section-number">6.2</span> Operational Problem</h2>
<p>Sean, the production engineer, asks a question that matters long before any answer gets generated: <em>“Can you trust the text this archive extracted — even from a report that was scanned instead of born digital?”</em> Every one of the 76 Utah FORGE reports used in this book is digital-native — extracting all 76 with Chapter 1’s own <code>extract_text()</code> confirms zero unparsed PDFs. (The companion pipeline’s QA/QC pass reports the same result across 227 source files — the larger, pre-deduplication count from the raw public archive before Chapter 8’s <code>build_full_archive.py</code> collapsed it down to 76; that raw archive isn’t part of this book’s repository, so the 227-file figure isn’t independently checkable here.) You got lucky: WellEz, the software that generated these reports, embeds real character data on every page. Not every archive is this well-behaved. Faxed reports, reports scanned from paper files, and photos of a logbook page all produce PDFs with no character data at all — just a picture of text. Chapter 1’s <code>extract_text()</code> handled this gracefully (an empty string, not a crash), but a real, larger archive needs more than graceful failure: it needs OCR to recover the text, and a way to know whether to trust what OCR gives back.</p>
</section>
<section id="example-ddr-extract" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="example-ddr-extract"><span class="header-section-number">6.3</span> Example DDR extract</h2>
<div class="callout callout-style-default callout-note callout-titled" title="OCR output before and after quality gating">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>OCR output before and after quality gating
</div>
</div>
<div class="callout-body-container callout-body">
<pre><code>Clean digital extraction (this is what every Utah FORGE report gives):
  "During the slide lost tool face and became assembly became stuck"

Degraded OCR output from a hypothetical poor scan of the same line:
  "Dur1ng the s1ide los+ t00l face and became assembIy became stu(k"</code></pre>
<p>The second block is exactly the kind of text a naive pipeline would embed and index without complaint — and exactly the kind of text a quality gate should catch and route to a review queue instead. That degraded line is illustrative; further down, “Seeing it on a real scanned page” makes an actual scanned page from report #38 and runs the whole extract-fails → OCR → gate round-trip on it, no hypotheticals.</p>
</div>
</div>
</section>
<section id="theory" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="theory"><span class="header-section-number">6.4</span> Theory</h2>
<div class="callout callout-style-default callout-tip callout-titled" title="Engineering Translation: OCR">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Engineering Translation: OCR
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>OCR</strong> (Optical Character Recognition) is software that looks at a <em>picture</em> of text — a scanned page, a photo of a logbook — and reads the letters and numbers off it, the same way a person would, turning that picture into text a computer can search. It’s the step that recovers text from exactly the kind of PDF Chapter 1’s <code>extract_text()</code> returns nothing for.</p>
</div>
</div>
<p>Getting OCR to run is the easy part — <code>pytesseract</code>, cloud OCR APIs, and PDF-rendering libraries all do a competent job of turning a page image into text. The hard part, and the one that actually determines whether your downstream system is trustworthy, is deciding <strong>whether to trust the output at all</strong>. A quality gate scores OCR text against a handful of cheap heuristics — quick rule-of-thumb checks: is there enough text, is the alphabetic-to-symbol ratio sane, is there suspicious repeated garbage — and rejects anything that fails, routing it to manual review instead of silently indexing noise.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Engineering Translation: Quality gate">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Engineering Translation: Quality gate
</div>
</div>
<div class="callout-body-container callout-body">
<p>A <strong>quality gate</strong> is a mud check before you commit to pumping downhole: a handful of cheap tests run before you trust what comes next. Passing doesn’t prove the text is perfect, the same way a good mud check doesn’t prove there’s no problem downhole — it just screens out the obviously bad cases before they cost you.</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Engineering Translation: Flag">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Engineering Translation: Flag
</div>
</div>
<div class="callout-body-container callout-body">
<p>A <strong>flag</strong> here is one checkbox on an inspection form — “too little text” either applies or it doesn’t. One flag firing on its own usually isn’t grounds for rejection (a short, sparse-but-real report can trip one check honestly); it’s when <em>several</em> flags fire together that the page is actually suspect.</p>
</div>
</div>
<p>This chapter’s companion pipeline, <strong>DDR_UTAH_FORGE</strong>, implements exactly this pattern in <code>src/rag_pdf/ocr_quality.py</code> — even though, as noted above, this particular archive never needs to exercise it. That’s by design: the quality gate runs unconditionally on every extracted page, digital or scanned, as a defensive check. Its <code>evaluate_ocr_quality()</code> function checks four independent flags — <code>low_text_density</code>, <code>high_symbol_ratio</code>, <code>repeated_garbage</code>, <code>low_line_count</code> — and rejects a page only once <strong>two or more</strong> flags fire, so no single noisy-but-legitimate page (e.g.&nbsp;a short report with a lot of numeric data) gets discarded on one false positive.</p>
<pre><code>extracted text
   ↓
compute four flags
(low_text_density, high_symbol_ratio,
 repeated_garbage, low_line_count)
   ↓
count how many are True
   ↓
2 or more active?
   ↓
  yes -&gt; reject, flag for review
  no  -&gt; accept into index</code></pre>
</section>
<section id="implementation" class="level2" data-number="6.5">
<h2 data-number="6.5" class="anchored" data-anchor-id="implementation"><span class="header-section-number">6.5</span> Implementation</h2>
<section id="step-1-build-a-quality-gate-function" class="level3" data-number="6.5.1">
<h3 data-number="6.5.1" class="anchored" data-anchor-id="step-1-build-a-quality-gate-function"><span class="header-section-number">6.5.1</span> Step 1: build a quality-gate function</h3>
<p>Build a simplified version of the same idea.</p>
<p><strong>What problem are we solving?</strong></p>
<p>Decide whether a page’s extracted text is trustworthy enough to add to the search index, or whether it should be set aside for a human to check instead.</p>
<p><strong>Inputs</strong></p>
<ul>
<li>Extracted text (from OCR, or from Chapter 1’s digital extraction).</li>
<li>Thresholds: minimum characters, minimum alphabetic words, maximum symbol ratio, and how many flags must fire before rejecting.</li>
</ul>
<p><strong>Expected Output</strong></p>
<p>A dictionary reporting the decision and which specific checks failed, for example:</p>
<pre><code>{"reject_ocr": True, "flags": {"low_text_density": True, "high_symbol_ratio": True}}</code></pre>
<div id="c4a2a930" class="cell" data-execution_count="1">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># code/chapter_06/ocr_quality_gate.py</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> re</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> evaluate_ocr_quality(text: <span class="bu">str</span>, min_chars: <span class="bu">int</span> <span class="op">=</span> <span class="dv">200</span>,</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>                          min_alpha_words: <span class="bu">int</span> <span class="op">=</span> <span class="dv">30</span>,</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>                          max_symbol_ratio: <span class="bu">float</span> <span class="op">=</span> <span class="fl">0.35</span>,</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>                          reject_min_flags: <span class="bu">int</span> <span class="op">=</span> <span class="dv">2</span>) <span class="op">-&gt;</span> <span class="bu">dict</span>:</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>    alpha_tokens <span class="op">=</span> re.findall(<span class="vs">r"</span><span class="pp">[A-Za-z]</span><span class="op">+</span><span class="vs">"</span>, text)</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>    non_ws <span class="op">=</span> [c <span class="cf">for</span> c <span class="kw">in</span> text <span class="cf">if</span> <span class="kw">not</span> c.isspace()]</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>    noisy <span class="op">=</span> <span class="bu">sum</span>(<span class="dv">1</span> <span class="cf">for</span> c <span class="kw">in</span> non_ws <span class="cf">if</span> <span class="kw">not</span> c.isalnum() <span class="kw">and</span> c <span class="kw">not</span> <span class="kw">in</span> <span class="bu">set</span>(<span class="st">"%.,()/-:'"</span>))</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>    symbol_ratio <span class="op">=</span> noisy <span class="op">/</span> <span class="bu">max</span>(<span class="bu">len</span>(non_ws), <span class="dv">1</span>)</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>    flags <span class="op">=</span> {</span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>        <span class="st">"low_text_density"</span>: <span class="bu">len</span>(text) <span class="op">&lt;</span> min_chars <span class="kw">or</span> <span class="bu">len</span>(alpha_tokens) <span class="op">&lt;</span> min_alpha_words,</span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>        <span class="st">"high_symbol_ratio"</span>: symbol_ratio <span class="op">&gt;</span> max_symbol_ratio,</span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a>    active <span class="op">=</span> [k <span class="cf">for</span> k, v <span class="kw">in</span> flags.items() <span class="cf">if</span> v]</span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> {<span class="st">"reject_ocr"</span>: <span class="bu">len</span>(active) <span class="op">&gt;=</span> reject_min_flags, <span class="st">"flags"</span>: flags}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>What just happened?</strong></p>
<p>This measures two things about the text: how much of it is real, readable words (<code>low_text_density</code>), and how much of it is odd symbols that shouldn’t be there (<code>high_symbol_ratio</code>). Each check is a simple yes/no. Only when two or more of those checks say “yes, this looks wrong” does the function recommend rejecting the page — a single unusual character never sinks an otherwise legitimate report.</p>
<p>Test it against a real Utah FORGE report’s clean text (it should pass easily — that text has a healthy word count and almost no noise symbols) and against the corrupted example above (it should fail on both flags).</p>
<p>The full production version — including the repeated-garbage detector and line-count check — is in the companion repository at <code>src/rag_pdf/ocr_quality.py</code>, alongside <code>src/rag_pdf/rotation_handler.py</code> for detecting and correcting upside-down or sideways scans, and <code>src/rag_pdf/table_ocr_handoff.py</code> for the case where a <em>table</em> (not narrative text) needs OCR fallback.</p>
</section>
<section id="step-2-see-it-on-a-real-scanned-page" class="level3" data-number="6.5.2">
<h3 data-number="6.5.2" class="anchored" data-anchor-id="step-2-see-it-on-a-real-scanned-page"><span class="header-section-number">6.5.2</span> Step 2: see it on a real scanned page</h3>
<p>The gate scores text — but where does bad OCR text actually come from? This archive is entirely digital, so to see the whole problem end to end you have to make a scanned page first. <code>make_scanned_example.py</code> turns each page of a real report into a plain image and writes it back out as an image-only PDF: pictures of text, no character data, exactly what a scan of a paper report looks like to software.</p>
<p>Install the OCR tools (Chapter 6 only — nothing earlier needs them):</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="ex">pip</span> install pytesseract pdf2image</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="co"># plus the system tools they wrap:</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="co">#   macOS:   brew install tesseract poppler</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="co">#   Ubuntu:  apt install tesseract-ocr poppler-utils</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="co">#   Windows: install Tesseract (the UB-Mannheim build at</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="co">#            github.com/UB-Mannheim/tesseract/wiki) and Poppler for</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="co">#            Windows (github.com/oschwartz10612/poppler-windows/releases),</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="co">#            then add both installs' bin/ folders to your PATH. Reopen</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a><span class="co">#            your terminal afterward so the updated PATH takes effect.</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="callout callout-style-default callout-note callout-titled" title="These are optional system tools, not Python packages">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>These are optional system tools, not Python packages
</div>
</div>
<div class="callout-body-container callout-body">
<p>Unlike everything else <code>pip install</code>s, Tesseract and Poppler are separate programs your operating system needs to already have — <code>pip</code> can’t install them for you. If you’d rather not deal with system-level installs right now, that’s fine: everything else in this chapter (the quality gate itself, and its Practical/Field Notes sections against the archive’s existing digital text) runs without them. Only this specific round-trip — making a scanned image and OCR’ing it back — needs Tesseract and Poppler actually installed. Skip ahead to “Production Reality” and come back to this section once they’re in place.</p>
</div>
</div>
<p>Then run the round-trip — make the scanned page from report #38, try to extract it, OCR it, and gate both:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb6"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="ex">python</span> code/chapter_06/make_scanned_example.py</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="callout callout-style-default callout-note callout-titled" title="A real digital-vs-OCR round-trip on report #38">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>A real digital-vs-OCR round-trip on report #38
</div>
</div>
<div class="callout-body-container callout-body">
<pre><code>Digital extraction:   3851 chars   stuck line present: True
pdfplumber on scan:      0 chars   stuck line present: False
OCR on scan:          3376 chars   stuck line present: True

Quality gate:
  digital  reject=False  flags={'low_text_density': False, 'high_symbol_ratio': False}
  OCR      reject=False  flags={'low_text_density': False, 'high_symbol_ratio': False}</code></pre>
</div>
</div>
<p>Three real facts fall out of that run:</p>
<ul>
<li><strong>Chapter 1’s extraction returns nothing on a scan.</strong> <code>pdfplumber</code> on the image-only PDF recovers <strong>0 characters</strong> — there’s no character data to read, only a picture. That’s the exact failure a real archive’s scanned reports hit, reproduced here on a real FORGE page instead of a hypothetical one.</li>
<li><strong>OCR recovers the text.</strong> Tesseract reads 3,376 of the digital version’s 3,851 characters back off the image, and the stuck-pipe line comes through intact: <code>During the slide lost tool face and became assembly became stuck</code>.</li>
<li><strong>The gate passes clean OCR.</strong> This scan was sharp, so the recovered text is good and the gate accepts it — which is the point of a gate as much as rejection is: it has to wave good OCR through as readily as it stops bad OCR. The degraded line back in the Example section is the other half — what the gate catches when a scan <em>isn’t</em> this clean.</li>
</ul>
</section>
</section>
<section id="production-reality" class="level2" data-number="6.6">
<h2 data-number="6.6" class="anchored" data-anchor-id="production-reality"><span class="header-section-number">6.6</span> Production Reality</h2>
<p>This chapter’s quality gate answers one narrow question: should this specific page be trusted? It doesn’t answer what happens next. A real archive needs a plan for that too:</p>
<ul>
<li>a flagged page needs an actual person to review it — a gate only earns its keep if someone owns the review queue it creates, otherwise flagged pages just pile up unread</li>
<li>rotated or upside-down scans (common when a paper report goes into a scanner sideways) need correcting <em>before</em> OCR runs at all — that’s a separate step from quality scoring, handled by the companion <code>rotation_handler.py</code></li>
<li>handwritten margin notes on an otherwise-typed report often don’t OCR into anything usable — the gate will correctly flag them as low-density, but “OCR failed” and “this needs a human to transcribe handwriting” call for different follow-up</li>
<li>an archive spanning multiple regions or operators may include reports in more than one language, which changes which OCR language pack — and which quality thresholds — actually apply</li>
</ul>
<p>None of this shows up in the all-digital Utah FORGE archive, which is exactly why it’s easy to forget about until a real archive containing any of the above lands on your desk.</p>
</section>
<section id="practical-exercise" class="level2" data-number="6.7">
<h2 data-number="6.7" class="anchored" data-anchor-id="practical-exercise"><span class="header-section-number">6.7</span> Practical exercise</h2>
<p>🟢 <strong>Beginner</strong></p>
<p><strong>Try it yourself:</strong> Run <code>evaluate_ocr_quality()</code> against the extracted text of report #38 (clean) and the degraded example string above.</p>
<p><strong>You’ll know it worked when:</strong> the real report text passes cleanly, and you can explain, from the flags returned, exactly why the degraded text fails.</p>
</section>
<section id="field-notes" class="level2" data-number="6.8">
<h2 data-number="6.8" class="anchored" data-anchor-id="field-notes"><span class="header-section-number">6.8</span> Field notes</h2>
<div class="callout callout-style-default callout-warning callout-titled" title="🔧 Field notes: checking the gate doesn't cry wolf">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>🔧 Field notes: checking the gate doesn’t cry wolf
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Action:</strong> run <code>evaluate_ocr_quality()</code> against all ten real sample reports, including report #3 — the sparsest one in the archive, written before the well was even spudded, with most of its tables entirely empty.</p>
<p><strong>Result:</strong> every single report passes cleanly. Report #3, the thinnest of the ten, still has 2,235 characters and 361 alphabetic words — comfortably clear of the 200-character / 30-word thresholds:</p>
<pre><code>chars=2235 alpha_words=361 symbol_ratio=0.006  reject=False</code></pre>
<p><strong>Why:</strong> even a nearly-empty DDR carries a full page of section headers, column labels, and boilerplate (“WELL/JOB INFORMATION”, “PRESENT OPERATIONS”, table column names) regardless of how little actually happened that day. That structural text alone is enough to clear the density thresholds.</p>
<p><strong>Lesson:</strong> a quality gate is only trustworthy if it doesn’t also reject legitimate sparse content — a gate that flagged every quiet day as “probably OCR garbage” would be useless in practice, burying real pages under false alarms. Checking the gate against your <em>most</em> sparse real documents, not just your noisiest fake ones, is how you find that out before it costs you.</p>
</div>
</div>
</section>
<section id="challenge-exercise" class="level2" data-number="6.9">
<h2 data-number="6.9" class="anchored" data-anchor-id="challenge-exercise"><span class="header-section-number">6.9</span> Challenge exercise</h2>
<p>🟠 <strong>Intermediate</strong></p>
<p><strong>Challenge:</strong> This archive is 100% digital, so you can’t test the gate against a real scanned Utah FORGE page. Instead, write a small function that synthetically corrupts clean text (swap random characters for lookalikes, inject repeated tokens) at increasing severity, and find the corruption level at which <code>evaluate_ocr_quality()</code> starts rejecting it. This is a legitimate way to stress-test a quality gate before you ever encounter the real noisy data it’s meant to catch.</p>
</section>
<section id="key-takeaways" class="level2" data-number="6.10">
<h2 data-number="6.10" class="anchored" data-anchor-id="key-takeaways"><span class="header-section-number">6.10</span> Key takeaways</h2>
<ul>
<li>OCR quality gating is cheap, heuristic, and worth running unconditionally — even an archive that’s currently 100% digital may not stay that way, and the check costs almost nothing on clean text.</li>
<li>Require multiple independent signals to agree before rejecting a page; a single heuristic alone produces too many false positives.</li>
<li>Reject-and-flag-for-review beats silently-index-anyway every time traceability matters more than completeness.</li>
</ul>
</section>
<section id="repository-files" class="level2" data-number="6.11">
<h2 data-number="6.11" class="anchored" data-anchor-id="repository-files"><span class="header-section-number">6.11</span> Repository files</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>File</th>
<th>Purpose</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>code/chapter_06/ocr_quality_gate.py</code></td>
<td>Simplified OCR quality gate</td>
</tr>
<tr class="even">
<td><code>code/chapter_06/make_scanned_example.py</code></td>
<td>Make an image-only PDF from a real report, then OCR and gate it</td>
</tr>
<tr class="odd">
<td><code>DDR_UTAH_FORGE/src/rag_pdf/ocr_quality.py</code></td>
<td>Production quality gate (companion repo — requires DDR_UTAH_FORGE)</td>
</tr>
<tr class="even">
<td><code>DDR_UTAH_FORGE/src/rag_pdf/rotation_handler.py</code></td>
<td>Scan rotation detection (companion repo — requires DDR_UTAH_FORGE)</td>
</tr>
</tbody>
</table>
<div class="callout callout-style-default callout-caution callout-titled" title="CHECKPOINT — Chapter 6">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Caution</span>CHECKPOINT — Chapter 6
</div>
</div>
<div class="callout-body-container callout-body">
<ul class="task-list">
<li><label><input type="checkbox" checked="">Recognised when a DDR PDF needs OCR instead of direct extraction</label></li>
<li><label><input type="checkbox" checked="">Made a real scanned-style page from a digital report and recovered its text with OCR</label></li>
<li><label><input type="checkbox" checked="">Explained why raw OCR output can’t be trusted without scoring it first</label></li>
<li><label><input type="checkbox" checked="">Built a quality gate that rejects bad text before it reaches the index</label></li>
<li><label><input type="checkbox" checked="">Verified the gate doesn’t false-positive on legitimately sparse reports</label></li>
</ul>
</div>
</div>
<div class="built-box callout callout-style-default callout-tip callout-titled" title="✓ WHAT YOU BUILT">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>✓ WHAT YOU BUILT
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong><code>ocr_quality_gate.py</code></strong> — an OCR quality gate: score any extracted text against four cheap heuristics and decide, automatically, whether it’s trustworthy enough to index or needs a human to review it first.</p>
</div>
</div>
</section>
<section id="what-can-you-do-now-that-you-couldnt-do-before" class="level2" data-number="6.12">
<h2 data-number="6.12" class="anchored" data-anchor-id="what-can-you-do-now-that-you-couldnt-do-before"><span class="header-section-number">6.12</span> What can you do now that you couldn’t do before?</h2>
<p>You can tell, automatically, whether a page of extracted or OCR’d text is trustworthy enough to search on — and route the pages that aren’t to a human for review, instead of silently indexing garbage alongside good reports.</p>
</section>
<section id="suggested-next-step" class="level2" data-number="6.13">
<h2 data-number="6.13" class="anchored" data-anchor-id="suggested-next-step"><span class="header-section-number">6.13</span> Suggested next step</h2>
<p><strong>Coming up in Chapter 7:</strong> Once you trust the text coming out of OCR and digital extraction alike, the next question is how to break it into pieces small enough to embed and retrieve — without cutting a stuck-pipe narrative in half across two chunks. That’s Chapter 7.</p>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapters/chapter_05.html" class="pagination-link" aria-label="First RAG System">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">First RAG System</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapters/chapter_07.html" class="pagination-link" aria-label="Chunking That Respects Report Structure">
        <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Chunking That Respects Report Structure</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb9" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu"># Scanned Reports and OCR Quality Gates {#sec-chapter-06}</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>::: {.content-visible when-format="html"}</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>::: {.pipeline-diagram}</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="al">![](../figures/diagrams/pipeline_ch06_light.svg)</span>{.diagram-light width="160"}</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="al">![](../figures/diagrams/pipeline_ch06_dark.svg)</span>{.diagram-dark width="160"}</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>::: {.content-visible when-format="pdf"}</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a><span class="al">![](../figures/diagrams/pipeline_ch06.pdf)</span>{width="160" fig-align="center"}</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>::: {.chapter-status}</span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>Progress <span class="in">`██████░░░░░░░`</span> **6 / 13** &amp;nbsp;·&amp;nbsp; **Estimated time:** 45–60 min &amp;nbsp;·&amp;nbsp; **Difficulty:** 🟠 Intermediate</span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a><span class="fu">## Learning objectives</span></span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a>By the end of this chapter, you will be able to:</span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-22"><a href="#cb9-22" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Recognise when a DDR PDF has no extractable text and needs OCR.</span>
<span id="cb9-23"><a href="#cb9-23" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Make a scanned-style page from a digital report, recover its text with</span>
<span id="cb9-24"><a href="#cb9-24" aria-hidden="true" tabindex="-1"></a>  OCR, and score whether that text is trustworthy enough to index.</span>
<span id="cb9-25"><a href="#cb9-25" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Build a quality gate that rejects bad OCR output *before* it enters your</span>
<span id="cb9-26"><a href="#cb9-26" aria-hidden="true" tabindex="-1"></a>  search index, rather than trying to fix it after the fact.</span>
<span id="cb9-27"><a href="#cb9-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-28"><a href="#cb9-28" aria-hidden="true" tabindex="-1"></a><span class="fu">## Operational Problem</span></span>
<span id="cb9-29"><a href="#cb9-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-30"><a href="#cb9-30" aria-hidden="true" tabindex="-1"></a>Sean, the production engineer, asks a question that matters long before</span>
<span id="cb9-31"><a href="#cb9-31" aria-hidden="true" tabindex="-1"></a>any answer gets generated: *"Can you trust the text this archive</span>
<span id="cb9-32"><a href="#cb9-32" aria-hidden="true" tabindex="-1"></a>extracted — even from a report that was scanned instead of born</span>
<span id="cb9-33"><a href="#cb9-33" aria-hidden="true" tabindex="-1"></a>digital?"* Every one of the 76 Utah FORGE</span>
<span id="cb9-34"><a href="#cb9-34" aria-hidden="true" tabindex="-1"></a>reports used in this book is digital-native — extracting all 76 with</span>
<span id="cb9-35"><a href="#cb9-35" aria-hidden="true" tabindex="-1"></a>Chapter 1's own <span class="in">`extract_text()`</span> confirms zero unparsed PDFs. (The</span>
<span id="cb9-36"><a href="#cb9-36" aria-hidden="true" tabindex="-1"></a>companion pipeline's QA/QC pass reports the same result across 227</span>
<span id="cb9-37"><a href="#cb9-37" aria-hidden="true" tabindex="-1"></a>source files — the larger, pre-deduplication count from the raw public</span>
<span id="cb9-38"><a href="#cb9-38" aria-hidden="true" tabindex="-1"></a>archive before Chapter 8's <span class="in">`build_full_archive.py`</span> collapsed it down to</span>
<span id="cb9-39"><a href="#cb9-39" aria-hidden="true" tabindex="-1"></a>76; that raw archive isn't part of this book's repository, so the</span>
<span id="cb9-40"><a href="#cb9-40" aria-hidden="true" tabindex="-1"></a>227-file figure isn't independently checkable here.) You got lucky: WellEz,</span>
<span id="cb9-41"><a href="#cb9-41" aria-hidden="true" tabindex="-1"></a>the software that generated these reports, embeds real character data on</span>
<span id="cb9-42"><a href="#cb9-42" aria-hidden="true" tabindex="-1"></a>every page. Not every archive is this well-behaved. Faxed reports, reports</span>
<span id="cb9-43"><a href="#cb9-43" aria-hidden="true" tabindex="-1"></a>scanned from paper files, and photos of a logbook page all produce PDFs</span>
<span id="cb9-44"><a href="#cb9-44" aria-hidden="true" tabindex="-1"></a>with no character data at all — just a picture of text. Chapter 1's</span>
<span id="cb9-45"><a href="#cb9-45" aria-hidden="true" tabindex="-1"></a><span class="in">`extract_text()`</span> handled this gracefully (an empty string, not a crash),</span>
<span id="cb9-46"><a href="#cb9-46" aria-hidden="true" tabindex="-1"></a>but a real, larger archive needs more than graceful failure: it needs OCR</span>
<span id="cb9-47"><a href="#cb9-47" aria-hidden="true" tabindex="-1"></a>to recover the text, and a way to know whether to trust what OCR gives</span>
<span id="cb9-48"><a href="#cb9-48" aria-hidden="true" tabindex="-1"></a>back.</span>
<span id="cb9-49"><a href="#cb9-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-50"><a href="#cb9-50" aria-hidden="true" tabindex="-1"></a><span class="fu">## Example DDR extract</span></span>
<span id="cb9-51"><a href="#cb9-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-52"><a href="#cb9-52" aria-hidden="true" tabindex="-1"></a>::: {.callout-note title="OCR output before and after quality gating"}</span>
<span id="cb9-53"><a href="#cb9-53" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb9-54"><a href="#cb9-54" aria-hidden="true" tabindex="-1"></a><span class="in">Clean digital extraction (this is what every Utah FORGE report gives):</span></span>
<span id="cb9-55"><a href="#cb9-55" aria-hidden="true" tabindex="-1"></a><span class="in">  "During the slide lost tool face and became assembly became stuck"</span></span>
<span id="cb9-56"><a href="#cb9-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-57"><a href="#cb9-57" aria-hidden="true" tabindex="-1"></a><span class="in">Degraded OCR output from a hypothetical poor scan of the same line:</span></span>
<span id="cb9-58"><a href="#cb9-58" aria-hidden="true" tabindex="-1"></a><span class="in">  "Dur1ng the s1ide los+ t00l face and became assembIy became stu(k"</span></span>
<span id="cb9-59"><a href="#cb9-59" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb9-60"><a href="#cb9-60" aria-hidden="true" tabindex="-1"></a>The second block is exactly the kind of text a naive pipeline would embed</span>
<span id="cb9-61"><a href="#cb9-61" aria-hidden="true" tabindex="-1"></a>and index without complaint — and exactly the kind of text a quality gate</span>
<span id="cb9-62"><a href="#cb9-62" aria-hidden="true" tabindex="-1"></a>should catch and route to a review queue instead. That degraded line is</span>
<span id="cb9-63"><a href="#cb9-63" aria-hidden="true" tabindex="-1"></a>illustrative; further down, "Seeing it on a real scanned page" makes an</span>
<span id="cb9-64"><a href="#cb9-64" aria-hidden="true" tabindex="-1"></a>actual scanned page from report #38 and runs the whole extract-fails →</span>
<span id="cb9-65"><a href="#cb9-65" aria-hidden="true" tabindex="-1"></a>OCR → gate round-trip on it, no hypotheticals.</span>
<span id="cb9-66"><a href="#cb9-66" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb9-67"><a href="#cb9-67" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-68"><a href="#cb9-68" aria-hidden="true" tabindex="-1"></a><span class="fu">## Theory</span></span>
<span id="cb9-69"><a href="#cb9-69" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-70"><a href="#cb9-70" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip title="Engineering Translation: OCR"}</span>
<span id="cb9-71"><a href="#cb9-71" aria-hidden="true" tabindex="-1"></a>**OCR** (Optical Character Recognition) is software that looks at a</span>
<span id="cb9-72"><a href="#cb9-72" aria-hidden="true" tabindex="-1"></a>*picture* of text — a scanned page, a photo of a logbook — and reads the</span>
<span id="cb9-73"><a href="#cb9-73" aria-hidden="true" tabindex="-1"></a>letters and numbers off it, the same way a person would, turning that</span>
<span id="cb9-74"><a href="#cb9-74" aria-hidden="true" tabindex="-1"></a>picture into text a computer can search. It's the step that recovers</span>
<span id="cb9-75"><a href="#cb9-75" aria-hidden="true" tabindex="-1"></a>text from exactly the kind of PDF Chapter 1's <span class="in">`extract_text()`</span> returns</span>
<span id="cb9-76"><a href="#cb9-76" aria-hidden="true" tabindex="-1"></a>nothing for.</span>
<span id="cb9-77"><a href="#cb9-77" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb9-78"><a href="#cb9-78" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-79"><a href="#cb9-79" aria-hidden="true" tabindex="-1"></a>Getting OCR to run is the easy part — <span class="in">`pytesseract`</span>, cloud OCR APIs, and</span>
<span id="cb9-80"><a href="#cb9-80" aria-hidden="true" tabindex="-1"></a>PDF-rendering libraries all do a competent job of turning a page image</span>
<span id="cb9-81"><a href="#cb9-81" aria-hidden="true" tabindex="-1"></a>into text. The hard part, and the one that actually determines whether</span>
<span id="cb9-82"><a href="#cb9-82" aria-hidden="true" tabindex="-1"></a>your downstream system is trustworthy, is deciding **whether to trust the</span>
<span id="cb9-83"><a href="#cb9-83" aria-hidden="true" tabindex="-1"></a>output at all**. A quality gate scores OCR text against a handful of cheap</span>
<span id="cb9-84"><a href="#cb9-84" aria-hidden="true" tabindex="-1"></a>heuristics — quick rule-of-thumb checks: is there enough text, is the alphabetic-to-symbol ratio</span>
<span id="cb9-85"><a href="#cb9-85" aria-hidden="true" tabindex="-1"></a>sane, is there suspicious repeated garbage — and rejects anything that</span>
<span id="cb9-86"><a href="#cb9-86" aria-hidden="true" tabindex="-1"></a>fails, routing it to manual review instead of silently indexing noise.</span>
<span id="cb9-87"><a href="#cb9-87" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-88"><a href="#cb9-88" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip title="Engineering Translation: Quality gate"}</span>
<span id="cb9-89"><a href="#cb9-89" aria-hidden="true" tabindex="-1"></a>A **quality gate** is a mud check before you commit to pumping downhole:</span>
<span id="cb9-90"><a href="#cb9-90" aria-hidden="true" tabindex="-1"></a>a handful of cheap tests run before you trust what comes next. Passing</span>
<span id="cb9-91"><a href="#cb9-91" aria-hidden="true" tabindex="-1"></a>doesn't prove the text is perfect, the same way a good mud check doesn't</span>
<span id="cb9-92"><a href="#cb9-92" aria-hidden="true" tabindex="-1"></a>prove there's no problem downhole — it just screens out the obviously bad</span>
<span id="cb9-93"><a href="#cb9-93" aria-hidden="true" tabindex="-1"></a>cases before they cost you.</span>
<span id="cb9-94"><a href="#cb9-94" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb9-95"><a href="#cb9-95" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-96"><a href="#cb9-96" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip title="Engineering Translation: Flag"}</span>
<span id="cb9-97"><a href="#cb9-97" aria-hidden="true" tabindex="-1"></a>A **flag** here is one checkbox on an inspection form — "too little text"</span>
<span id="cb9-98"><a href="#cb9-98" aria-hidden="true" tabindex="-1"></a>either applies or it doesn't. One flag firing on its own usually isn't</span>
<span id="cb9-99"><a href="#cb9-99" aria-hidden="true" tabindex="-1"></a>grounds for rejection (a short, sparse-but-real report can trip one check</span>
<span id="cb9-100"><a href="#cb9-100" aria-hidden="true" tabindex="-1"></a>honestly); it's when *several* flags fire together that the page is</span>
<span id="cb9-101"><a href="#cb9-101" aria-hidden="true" tabindex="-1"></a>actually suspect.</span>
<span id="cb9-102"><a href="#cb9-102" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb9-103"><a href="#cb9-103" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-104"><a href="#cb9-104" aria-hidden="true" tabindex="-1"></a>This chapter's companion pipeline, **DDR_UTAH_FORGE**, implements exactly</span>
<span id="cb9-105"><a href="#cb9-105" aria-hidden="true" tabindex="-1"></a>this pattern in <span class="in">`src/rag_pdf/ocr_quality.py`</span> — even though, as noted</span>
<span id="cb9-106"><a href="#cb9-106" aria-hidden="true" tabindex="-1"></a>above, this particular archive never needs to exercise it. That's by</span>
<span id="cb9-107"><a href="#cb9-107" aria-hidden="true" tabindex="-1"></a>design: the quality gate runs unconditionally on every extracted page,</span>
<span id="cb9-108"><a href="#cb9-108" aria-hidden="true" tabindex="-1"></a>digital or scanned, as a defensive check. Its <span class="in">`evaluate_ocr_quality()`</span></span>
<span id="cb9-109"><a href="#cb9-109" aria-hidden="true" tabindex="-1"></a>function checks four independent flags — <span class="in">`low_text_density`</span>,</span>
<span id="cb9-110"><a href="#cb9-110" aria-hidden="true" tabindex="-1"></a><span class="in">`high_symbol_ratio`</span>, <span class="in">`repeated_garbage`</span>, <span class="in">`low_line_count`</span> — and rejects a</span>
<span id="cb9-111"><a href="#cb9-111" aria-hidden="true" tabindex="-1"></a>page only once **two or more** flags fire, so no single noisy-but-legitimate</span>
<span id="cb9-112"><a href="#cb9-112" aria-hidden="true" tabindex="-1"></a>page (e.g. a short report with a lot of numeric data) gets discarded on</span>
<span id="cb9-113"><a href="#cb9-113" aria-hidden="true" tabindex="-1"></a>one false positive.</span>
<span id="cb9-114"><a href="#cb9-114" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-115"><a href="#cb9-115" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb9-116"><a href="#cb9-116" aria-hidden="true" tabindex="-1"></a><span class="in">extracted text</span></span>
<span id="cb9-117"><a href="#cb9-117" aria-hidden="true" tabindex="-1"></a><span class="in">   ↓</span></span>
<span id="cb9-118"><a href="#cb9-118" aria-hidden="true" tabindex="-1"></a><span class="in">compute four flags</span></span>
<span id="cb9-119"><a href="#cb9-119" aria-hidden="true" tabindex="-1"></a><span class="in">(low_text_density, high_symbol_ratio,</span></span>
<span id="cb9-120"><a href="#cb9-120" aria-hidden="true" tabindex="-1"></a><span class="in"> repeated_garbage, low_line_count)</span></span>
<span id="cb9-121"><a href="#cb9-121" aria-hidden="true" tabindex="-1"></a><span class="in">   ↓</span></span>
<span id="cb9-122"><a href="#cb9-122" aria-hidden="true" tabindex="-1"></a><span class="in">count how many are True</span></span>
<span id="cb9-123"><a href="#cb9-123" aria-hidden="true" tabindex="-1"></a><span class="in">   ↓</span></span>
<span id="cb9-124"><a href="#cb9-124" aria-hidden="true" tabindex="-1"></a><span class="in">2 or more active?</span></span>
<span id="cb9-125"><a href="#cb9-125" aria-hidden="true" tabindex="-1"></a><span class="in">   ↓</span></span>
<span id="cb9-126"><a href="#cb9-126" aria-hidden="true" tabindex="-1"></a><span class="in">  yes -&gt; reject, flag for review</span></span>
<span id="cb9-127"><a href="#cb9-127" aria-hidden="true" tabindex="-1"></a><span class="in">  no  -&gt; accept into index</span></span>
<span id="cb9-128"><a href="#cb9-128" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb9-129"><a href="#cb9-129" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-130"><a href="#cb9-130" aria-hidden="true" tabindex="-1"></a><span class="fu">## Implementation</span></span>
<span id="cb9-131"><a href="#cb9-131" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-132"><a href="#cb9-132" aria-hidden="true" tabindex="-1"></a><span class="fu">### Step 1: build a quality-gate function</span></span>
<span id="cb9-133"><a href="#cb9-133" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-134"><a href="#cb9-134" aria-hidden="true" tabindex="-1"></a>Build a simplified version of the same idea.</span>
<span id="cb9-135"><a href="#cb9-135" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-136"><a href="#cb9-136" aria-hidden="true" tabindex="-1"></a>**What problem are we solving?**</span>
<span id="cb9-137"><a href="#cb9-137" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-138"><a href="#cb9-138" aria-hidden="true" tabindex="-1"></a>Decide whether a page's extracted text is trustworthy enough to add to</span>
<span id="cb9-139"><a href="#cb9-139" aria-hidden="true" tabindex="-1"></a>the search index, or whether it should be set aside for a human to check</span>
<span id="cb9-140"><a href="#cb9-140" aria-hidden="true" tabindex="-1"></a>instead.</span>
<span id="cb9-141"><a href="#cb9-141" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-142"><a href="#cb9-142" aria-hidden="true" tabindex="-1"></a>**Inputs**</span>
<span id="cb9-143"><a href="#cb9-143" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-144"><a href="#cb9-144" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Extracted text (from OCR, or from Chapter 1's digital extraction).</span>
<span id="cb9-145"><a href="#cb9-145" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Thresholds: minimum characters, minimum alphabetic words, maximum</span>
<span id="cb9-146"><a href="#cb9-146" aria-hidden="true" tabindex="-1"></a>  symbol ratio, and how many flags must fire before rejecting.</span>
<span id="cb9-147"><a href="#cb9-147" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-148"><a href="#cb9-148" aria-hidden="true" tabindex="-1"></a>**Expected Output**</span>
<span id="cb9-149"><a href="#cb9-149" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-150"><a href="#cb9-150" aria-hidden="true" tabindex="-1"></a>A dictionary reporting the decision and which specific checks failed, for</span>
<span id="cb9-151"><a href="#cb9-151" aria-hidden="true" tabindex="-1"></a>example:</span>
<span id="cb9-152"><a href="#cb9-152" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-153"><a href="#cb9-153" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb9-154"><a href="#cb9-154" aria-hidden="true" tabindex="-1"></a><span class="in">{"reject_ocr": True, "flags": {"low_text_density": True, "high_symbol_ratio": True}}</span></span>
<span id="cb9-155"><a href="#cb9-155" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb9-156"><a href="#cb9-156" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-159"><a href="#cb9-159" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb9-160"><a href="#cb9-160" aria-hidden="true" tabindex="-1"></a><span class="co">#| eval: false</span></span>
<span id="cb9-161"><a href="#cb9-161" aria-hidden="true" tabindex="-1"></a><span class="co"># code/chapter_06/ocr_quality_gate.py</span></span>
<span id="cb9-162"><a href="#cb9-162" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> re</span>
<span id="cb9-163"><a href="#cb9-163" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-164"><a href="#cb9-164" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> evaluate_ocr_quality(text: <span class="bu">str</span>, min_chars: <span class="bu">int</span> <span class="op">=</span> <span class="dv">200</span>,</span>
<span id="cb9-165"><a href="#cb9-165" aria-hidden="true" tabindex="-1"></a>                          min_alpha_words: <span class="bu">int</span> <span class="op">=</span> <span class="dv">30</span>,</span>
<span id="cb9-166"><a href="#cb9-166" aria-hidden="true" tabindex="-1"></a>                          max_symbol_ratio: <span class="bu">float</span> <span class="op">=</span> <span class="fl">0.35</span>,</span>
<span id="cb9-167"><a href="#cb9-167" aria-hidden="true" tabindex="-1"></a>                          reject_min_flags: <span class="bu">int</span> <span class="op">=</span> <span class="dv">2</span>) <span class="op">-&gt;</span> <span class="bu">dict</span>:</span>
<span id="cb9-168"><a href="#cb9-168" aria-hidden="true" tabindex="-1"></a>    alpha_tokens <span class="op">=</span> re.findall(<span class="vs">r"</span><span class="pp">[A-Za-z]</span><span class="op">+</span><span class="vs">"</span>, text)</span>
<span id="cb9-169"><a href="#cb9-169" aria-hidden="true" tabindex="-1"></a>    non_ws <span class="op">=</span> [c <span class="cf">for</span> c <span class="kw">in</span> text <span class="cf">if</span> <span class="kw">not</span> c.isspace()]</span>
<span id="cb9-170"><a href="#cb9-170" aria-hidden="true" tabindex="-1"></a>    noisy <span class="op">=</span> <span class="bu">sum</span>(<span class="dv">1</span> <span class="cf">for</span> c <span class="kw">in</span> non_ws <span class="cf">if</span> <span class="kw">not</span> c.isalnum() <span class="kw">and</span> c <span class="kw">not</span> <span class="kw">in</span> <span class="bu">set</span>(<span class="st">"%.,()/-:'"</span>))</span>
<span id="cb9-171"><a href="#cb9-171" aria-hidden="true" tabindex="-1"></a>    symbol_ratio <span class="op">=</span> noisy <span class="op">/</span> <span class="bu">max</span>(<span class="bu">len</span>(non_ws), <span class="dv">1</span>)</span>
<span id="cb9-172"><a href="#cb9-172" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-173"><a href="#cb9-173" aria-hidden="true" tabindex="-1"></a>    flags <span class="op">=</span> {</span>
<span id="cb9-174"><a href="#cb9-174" aria-hidden="true" tabindex="-1"></a>        <span class="st">"low_text_density"</span>: <span class="bu">len</span>(text) <span class="op">&lt;</span> min_chars <span class="kw">or</span> <span class="bu">len</span>(alpha_tokens) <span class="op">&lt;</span> min_alpha_words,</span>
<span id="cb9-175"><a href="#cb9-175" aria-hidden="true" tabindex="-1"></a>        <span class="st">"high_symbol_ratio"</span>: symbol_ratio <span class="op">&gt;</span> max_symbol_ratio,</span>
<span id="cb9-176"><a href="#cb9-176" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb9-177"><a href="#cb9-177" aria-hidden="true" tabindex="-1"></a>    active <span class="op">=</span> [k <span class="cf">for</span> k, v <span class="kw">in</span> flags.items() <span class="cf">if</span> v]</span>
<span id="cb9-178"><a href="#cb9-178" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> {<span class="st">"reject_ocr"</span>: <span class="bu">len</span>(active) <span class="op">&gt;=</span> reject_min_flags, <span class="st">"flags"</span>: flags}</span>
<span id="cb9-179"><a href="#cb9-179" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb9-180"><a href="#cb9-180" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-181"><a href="#cb9-181" aria-hidden="true" tabindex="-1"></a>**What just happened?**</span>
<span id="cb9-182"><a href="#cb9-182" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-183"><a href="#cb9-183" aria-hidden="true" tabindex="-1"></a>This measures two things about the text: how much of it is real,</span>
<span id="cb9-184"><a href="#cb9-184" aria-hidden="true" tabindex="-1"></a>readable words (<span class="in">`low_text_density`</span>), and how much of it is odd symbols</span>
<span id="cb9-185"><a href="#cb9-185" aria-hidden="true" tabindex="-1"></a>that shouldn't be there (<span class="in">`high_symbol_ratio`</span>). Each check is a simple</span>
<span id="cb9-186"><a href="#cb9-186" aria-hidden="true" tabindex="-1"></a>yes/no. Only when two or more of those checks say "yes, this looks</span>
<span id="cb9-187"><a href="#cb9-187" aria-hidden="true" tabindex="-1"></a>wrong" does the function recommend rejecting the page — a single unusual</span>
<span id="cb9-188"><a href="#cb9-188" aria-hidden="true" tabindex="-1"></a>character never sinks an otherwise legitimate report.</span>
<span id="cb9-189"><a href="#cb9-189" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-190"><a href="#cb9-190" aria-hidden="true" tabindex="-1"></a>Test it against a real Utah FORGE report's clean text (it should pass</span>
<span id="cb9-191"><a href="#cb9-191" aria-hidden="true" tabindex="-1"></a>easily — that text has a healthy word count and almost no noise symbols)</span>
<span id="cb9-192"><a href="#cb9-192" aria-hidden="true" tabindex="-1"></a>and against the corrupted example above (it should fail on both flags).</span>
<span id="cb9-193"><a href="#cb9-193" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-194"><a href="#cb9-194" aria-hidden="true" tabindex="-1"></a>The full production version — including the repeated-garbage detector and</span>
<span id="cb9-195"><a href="#cb9-195" aria-hidden="true" tabindex="-1"></a>line-count check — is in the companion repository at</span>
<span id="cb9-196"><a href="#cb9-196" aria-hidden="true" tabindex="-1"></a><span class="in">`src/rag_pdf/ocr_quality.py`</span>, alongside <span class="in">`src/rag_pdf/rotation_handler.py`</span></span>
<span id="cb9-197"><a href="#cb9-197" aria-hidden="true" tabindex="-1"></a>for detecting and correcting upside-down or sideways scans, and</span>
<span id="cb9-198"><a href="#cb9-198" aria-hidden="true" tabindex="-1"></a><span class="in">`src/rag_pdf/table_ocr_handoff.py`</span> for the case where a *table* (not</span>
<span id="cb9-199"><a href="#cb9-199" aria-hidden="true" tabindex="-1"></a>narrative text) needs OCR fallback.</span>
<span id="cb9-200"><a href="#cb9-200" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-201"><a href="#cb9-201" aria-hidden="true" tabindex="-1"></a><span class="fu">### Step 2: see it on a real scanned page</span></span>
<span id="cb9-202"><a href="#cb9-202" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-203"><a href="#cb9-203" aria-hidden="true" tabindex="-1"></a>The gate scores text — but where does bad OCR text actually come from?</span>
<span id="cb9-204"><a href="#cb9-204" aria-hidden="true" tabindex="-1"></a>This archive is entirely digital, so to see the whole problem end to end</span>
<span id="cb9-205"><a href="#cb9-205" aria-hidden="true" tabindex="-1"></a>you have to make a scanned page first. <span class="in">`make_scanned_example.py`</span></span>
<span id="cb9-206"><a href="#cb9-206" aria-hidden="true" tabindex="-1"></a>turns each page of a real report into a plain image and writes it back out as an</span>
<span id="cb9-207"><a href="#cb9-207" aria-hidden="true" tabindex="-1"></a>image-only PDF: pictures of text, no character data, exactly what a scan</span>
<span id="cb9-208"><a href="#cb9-208" aria-hidden="true" tabindex="-1"></a>of a paper report looks like to software.</span>
<span id="cb9-209"><a href="#cb9-209" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-210"><a href="#cb9-210" aria-hidden="true" tabindex="-1"></a>Install the OCR tools (Chapter 6 only — nothing earlier needs them):</span>
<span id="cb9-211"><a href="#cb9-211" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-212"><a href="#cb9-212" aria-hidden="true" tabindex="-1"></a><span class="in">```bash</span></span>
<span id="cb9-213"><a href="#cb9-213" aria-hidden="true" tabindex="-1"></a><span class="ex">pip</span> install pytesseract pdf2image</span>
<span id="cb9-214"><a href="#cb9-214" aria-hidden="true" tabindex="-1"></a><span class="co"># plus the system tools they wrap:</span></span>
<span id="cb9-215"><a href="#cb9-215" aria-hidden="true" tabindex="-1"></a><span class="co">#   macOS:   brew install tesseract poppler</span></span>
<span id="cb9-216"><a href="#cb9-216" aria-hidden="true" tabindex="-1"></a><span class="co">#   Ubuntu:  apt install tesseract-ocr poppler-utils</span></span>
<span id="cb9-217"><a href="#cb9-217" aria-hidden="true" tabindex="-1"></a><span class="co">#   Windows: install Tesseract (the UB-Mannheim build at</span></span>
<span id="cb9-218"><a href="#cb9-218" aria-hidden="true" tabindex="-1"></a><span class="co">#            github.com/UB-Mannheim/tesseract/wiki) and Poppler for</span></span>
<span id="cb9-219"><a href="#cb9-219" aria-hidden="true" tabindex="-1"></a><span class="co">#            Windows (github.com/oschwartz10612/poppler-windows/releases),</span></span>
<span id="cb9-220"><a href="#cb9-220" aria-hidden="true" tabindex="-1"></a><span class="co">#            then add both installs' bin/ folders to your PATH. Reopen</span></span>
<span id="cb9-221"><a href="#cb9-221" aria-hidden="true" tabindex="-1"></a><span class="co">#            your terminal afterward so the updated PATH takes effect.</span></span>
<span id="cb9-222"><a href="#cb9-222" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb9-223"><a href="#cb9-223" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-224"><a href="#cb9-224" aria-hidden="true" tabindex="-1"></a>::: {.callout-note title="These are optional system tools, not Python packages"}</span>
<span id="cb9-225"><a href="#cb9-225" aria-hidden="true" tabindex="-1"></a>Unlike everything else <span class="in">`pip install`</span>s, Tesseract and Poppler are separate</span>
<span id="cb9-226"><a href="#cb9-226" aria-hidden="true" tabindex="-1"></a>programs your operating system needs to already have — <span class="in">`pip`</span> can't</span>
<span id="cb9-227"><a href="#cb9-227" aria-hidden="true" tabindex="-1"></a>install them for you. If you'd rather not deal with system-level installs</span>
<span id="cb9-228"><a href="#cb9-228" aria-hidden="true" tabindex="-1"></a>right now, that's fine: everything else in this chapter (the quality gate</span>
<span id="cb9-229"><a href="#cb9-229" aria-hidden="true" tabindex="-1"></a>itself, and its Practical/Field Notes sections against the archive's</span>
<span id="cb9-230"><a href="#cb9-230" aria-hidden="true" tabindex="-1"></a>existing digital text) runs without them. Only this specific round-trip —</span>
<span id="cb9-231"><a href="#cb9-231" aria-hidden="true" tabindex="-1"></a>making a scanned image and OCR'ing it back — needs Tesseract and Poppler</span>
<span id="cb9-232"><a href="#cb9-232" aria-hidden="true" tabindex="-1"></a>actually installed. Skip ahead to "Production Reality" and come back to</span>
<span id="cb9-233"><a href="#cb9-233" aria-hidden="true" tabindex="-1"></a>this section once they're in place.</span>
<span id="cb9-234"><a href="#cb9-234" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb9-235"><a href="#cb9-235" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-236"><a href="#cb9-236" aria-hidden="true" tabindex="-1"></a>Then run the round-trip — make the scanned page from report #38, try to</span>
<span id="cb9-237"><a href="#cb9-237" aria-hidden="true" tabindex="-1"></a>extract it, OCR it, and gate both:</span>
<span id="cb9-238"><a href="#cb9-238" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-239"><a href="#cb9-239" aria-hidden="true" tabindex="-1"></a><span class="in">```bash</span></span>
<span id="cb9-240"><a href="#cb9-240" aria-hidden="true" tabindex="-1"></a><span class="ex">python</span> code/chapter_06/make_scanned_example.py</span>
<span id="cb9-241"><a href="#cb9-241" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb9-242"><a href="#cb9-242" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-243"><a href="#cb9-243" aria-hidden="true" tabindex="-1"></a>::: {.callout-note title="A real digital-vs-OCR round-trip on report #38"}</span>
<span id="cb9-244"><a href="#cb9-244" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb9-245"><a href="#cb9-245" aria-hidden="true" tabindex="-1"></a><span class="in">Digital extraction:   3851 chars   stuck line present: True</span></span>
<span id="cb9-246"><a href="#cb9-246" aria-hidden="true" tabindex="-1"></a><span class="in">pdfplumber on scan:      0 chars   stuck line present: False</span></span>
<span id="cb9-247"><a href="#cb9-247" aria-hidden="true" tabindex="-1"></a><span class="in">OCR on scan:          3376 chars   stuck line present: True</span></span>
<span id="cb9-248"><a href="#cb9-248" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-249"><a href="#cb9-249" aria-hidden="true" tabindex="-1"></a><span class="in">Quality gate:</span></span>
<span id="cb9-250"><a href="#cb9-250" aria-hidden="true" tabindex="-1"></a><span class="in">  digital  reject=False  flags={'low_text_density': False, 'high_symbol_ratio': False}</span></span>
<span id="cb9-251"><a href="#cb9-251" aria-hidden="true" tabindex="-1"></a><span class="in">  OCR      reject=False  flags={'low_text_density': False, 'high_symbol_ratio': False}</span></span>
<span id="cb9-252"><a href="#cb9-252" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb9-253"><a href="#cb9-253" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb9-254"><a href="#cb9-254" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-255"><a href="#cb9-255" aria-hidden="true" tabindex="-1"></a>Three real facts fall out of that run:</span>
<span id="cb9-256"><a href="#cb9-256" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-257"><a href="#cb9-257" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Chapter 1's extraction returns nothing on a scan.** <span class="in">`pdfplumber`</span> on</span>
<span id="cb9-258"><a href="#cb9-258" aria-hidden="true" tabindex="-1"></a>  the image-only PDF recovers **0 characters** — there's no character</span>
<span id="cb9-259"><a href="#cb9-259" aria-hidden="true" tabindex="-1"></a>  data to read, only a picture. That's the exact failure a real archive's</span>
<span id="cb9-260"><a href="#cb9-260" aria-hidden="true" tabindex="-1"></a>  scanned reports hit, reproduced here on a real FORGE page instead of a</span>
<span id="cb9-261"><a href="#cb9-261" aria-hidden="true" tabindex="-1"></a>  hypothetical one.</span>
<span id="cb9-262"><a href="#cb9-262" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**OCR recovers the text.** Tesseract reads 3,376 of the digital</span>
<span id="cb9-263"><a href="#cb9-263" aria-hidden="true" tabindex="-1"></a>  version's 3,851 characters back off the image, and the stuck-pipe line</span>
<span id="cb9-264"><a href="#cb9-264" aria-hidden="true" tabindex="-1"></a>  comes through intact: `During the slide lost tool face and became</span>
<span id="cb9-265"><a href="#cb9-265" aria-hidden="true" tabindex="-1"></a>  assembly became stuck`.</span>
<span id="cb9-266"><a href="#cb9-266" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**The gate passes clean OCR.** This scan was sharp, so the recovered</span>
<span id="cb9-267"><a href="#cb9-267" aria-hidden="true" tabindex="-1"></a>  text is good and the gate accepts it — which is the point of a gate as</span>
<span id="cb9-268"><a href="#cb9-268" aria-hidden="true" tabindex="-1"></a>  much as rejection is: it has to wave good OCR through as readily as it</span>
<span id="cb9-269"><a href="#cb9-269" aria-hidden="true" tabindex="-1"></a>  stops bad OCR. The degraded line back in the Example section is the</span>
<span id="cb9-270"><a href="#cb9-270" aria-hidden="true" tabindex="-1"></a>  other half — what the gate catches when a scan *isn't* this clean.</span>
<span id="cb9-271"><a href="#cb9-271" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-272"><a href="#cb9-272" aria-hidden="true" tabindex="-1"></a><span class="fu">## Production Reality</span></span>
<span id="cb9-273"><a href="#cb9-273" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-274"><a href="#cb9-274" aria-hidden="true" tabindex="-1"></a>This chapter's quality gate answers one narrow question: should this</span>
<span id="cb9-275"><a href="#cb9-275" aria-hidden="true" tabindex="-1"></a>specific page be trusted? It doesn't answer what happens next. A real</span>
<span id="cb9-276"><a href="#cb9-276" aria-hidden="true" tabindex="-1"></a>archive needs a plan for that too:</span>
<span id="cb9-277"><a href="#cb9-277" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-278"><a href="#cb9-278" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>a flagged page needs an actual person to review it — a gate only earns</span>
<span id="cb9-279"><a href="#cb9-279" aria-hidden="true" tabindex="-1"></a>  its keep if someone owns the review queue it creates, otherwise flagged</span>
<span id="cb9-280"><a href="#cb9-280" aria-hidden="true" tabindex="-1"></a>  pages just pile up unread</span>
<span id="cb9-281"><a href="#cb9-281" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>rotated or upside-down scans (common when a paper report goes into a</span>
<span id="cb9-282"><a href="#cb9-282" aria-hidden="true" tabindex="-1"></a>  scanner sideways) need correcting *before* OCR runs at all — that's a</span>
<span id="cb9-283"><a href="#cb9-283" aria-hidden="true" tabindex="-1"></a>  separate step from quality scoring, handled by the companion</span>
<span id="cb9-284"><a href="#cb9-284" aria-hidden="true" tabindex="-1"></a>  <span class="in">`rotation_handler.py`</span></span>
<span id="cb9-285"><a href="#cb9-285" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>handwritten margin notes on an otherwise-typed report often don't OCR</span>
<span id="cb9-286"><a href="#cb9-286" aria-hidden="true" tabindex="-1"></a>  into anything usable — the gate will correctly flag them as</span>
<span id="cb9-287"><a href="#cb9-287" aria-hidden="true" tabindex="-1"></a>  low-density, but "OCR failed" and "this needs a human to transcribe</span>
<span id="cb9-288"><a href="#cb9-288" aria-hidden="true" tabindex="-1"></a>  handwriting" call for different follow-up</span>
<span id="cb9-289"><a href="#cb9-289" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>an archive spanning multiple regions or operators may include reports</span>
<span id="cb9-290"><a href="#cb9-290" aria-hidden="true" tabindex="-1"></a>  in more than one language, which changes which OCR language pack — and</span>
<span id="cb9-291"><a href="#cb9-291" aria-hidden="true" tabindex="-1"></a>  which quality thresholds — actually apply</span>
<span id="cb9-292"><a href="#cb9-292" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-293"><a href="#cb9-293" aria-hidden="true" tabindex="-1"></a>None of this shows up in the all-digital Utah FORGE archive, which is</span>
<span id="cb9-294"><a href="#cb9-294" aria-hidden="true" tabindex="-1"></a>exactly why it's easy to forget about until a real archive containing</span>
<span id="cb9-295"><a href="#cb9-295" aria-hidden="true" tabindex="-1"></a>any of the above lands on your desk.</span>
<span id="cb9-296"><a href="#cb9-296" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-297"><a href="#cb9-297" aria-hidden="true" tabindex="-1"></a><span class="fu">## Practical exercise</span></span>
<span id="cb9-298"><a href="#cb9-298" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-299"><a href="#cb9-299" aria-hidden="true" tabindex="-1"></a>🟢 **Beginner**</span>
<span id="cb9-300"><a href="#cb9-300" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-301"><a href="#cb9-301" aria-hidden="true" tabindex="-1"></a>**Try it yourself:** Run <span class="in">`evaluate_ocr_quality()`</span> against the extracted</span>
<span id="cb9-302"><a href="#cb9-302" aria-hidden="true" tabindex="-1"></a>text of report #38 (clean) and the degraded example string above.</span>
<span id="cb9-303"><a href="#cb9-303" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-304"><a href="#cb9-304" aria-hidden="true" tabindex="-1"></a>**You'll know it worked when:** the real report text passes cleanly, and</span>
<span id="cb9-305"><a href="#cb9-305" aria-hidden="true" tabindex="-1"></a>you can explain, from the flags returned, exactly why the degraded text</span>
<span id="cb9-306"><a href="#cb9-306" aria-hidden="true" tabindex="-1"></a>fails.</span>
<span id="cb9-307"><a href="#cb9-307" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-308"><a href="#cb9-308" aria-hidden="true" tabindex="-1"></a><span class="fu">## Field notes</span></span>
<span id="cb9-309"><a href="#cb9-309" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-310"><a href="#cb9-310" aria-hidden="true" tabindex="-1"></a>::: {.callout-warning title="🔧 Field notes: checking the gate doesn't cry wolf"}</span>
<span id="cb9-311"><a href="#cb9-311" aria-hidden="true" tabindex="-1"></a>**Action:** run <span class="in">`evaluate_ocr_quality()`</span> against all ten real sample</span>
<span id="cb9-312"><a href="#cb9-312" aria-hidden="true" tabindex="-1"></a>reports, including report #3 — the sparsest one in the archive, written</span>
<span id="cb9-313"><a href="#cb9-313" aria-hidden="true" tabindex="-1"></a>before the well was even spudded, with most of its tables entirely</span>
<span id="cb9-314"><a href="#cb9-314" aria-hidden="true" tabindex="-1"></a>empty.</span>
<span id="cb9-315"><a href="#cb9-315" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-316"><a href="#cb9-316" aria-hidden="true" tabindex="-1"></a>**Result:** every single report passes cleanly. Report #3, the thinnest</span>
<span id="cb9-317"><a href="#cb9-317" aria-hidden="true" tabindex="-1"></a>of the ten, still has 2,235 characters and 361 alphabetic words —</span>
<span id="cb9-318"><a href="#cb9-318" aria-hidden="true" tabindex="-1"></a>comfortably clear of the 200-character / 30-word thresholds:</span>
<span id="cb9-319"><a href="#cb9-319" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-320"><a href="#cb9-320" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb9-321"><a href="#cb9-321" aria-hidden="true" tabindex="-1"></a><span class="in">chars=2235 alpha_words=361 symbol_ratio=0.006  reject=False</span></span>
<span id="cb9-322"><a href="#cb9-322" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb9-323"><a href="#cb9-323" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-324"><a href="#cb9-324" aria-hidden="true" tabindex="-1"></a>**Why:** even a nearly-empty DDR carries a full page of section headers,</span>
<span id="cb9-325"><a href="#cb9-325" aria-hidden="true" tabindex="-1"></a>column labels, and boilerplate ("WELL/JOB INFORMATION", "PRESENT</span>
<span id="cb9-326"><a href="#cb9-326" aria-hidden="true" tabindex="-1"></a>OPERATIONS", table column names) regardless of how little actually</span>
<span id="cb9-327"><a href="#cb9-327" aria-hidden="true" tabindex="-1"></a>happened that day. That structural text alone is enough to clear the</span>
<span id="cb9-328"><a href="#cb9-328" aria-hidden="true" tabindex="-1"></a>density thresholds.</span>
<span id="cb9-329"><a href="#cb9-329" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-330"><a href="#cb9-330" aria-hidden="true" tabindex="-1"></a>**Lesson:** a quality gate is only trustworthy if it doesn't also reject</span>
<span id="cb9-331"><a href="#cb9-331" aria-hidden="true" tabindex="-1"></a>legitimate sparse content — a gate that flagged every quiet day as</span>
<span id="cb9-332"><a href="#cb9-332" aria-hidden="true" tabindex="-1"></a>"probably OCR garbage" would be useless in practice, burying real pages</span>
<span id="cb9-333"><a href="#cb9-333" aria-hidden="true" tabindex="-1"></a>under false alarms. Checking the gate against your *most* sparse real</span>
<span id="cb9-334"><a href="#cb9-334" aria-hidden="true" tabindex="-1"></a>documents, not just your noisiest fake ones, is how you find that out</span>
<span id="cb9-335"><a href="#cb9-335" aria-hidden="true" tabindex="-1"></a>before it costs you.</span>
<span id="cb9-336"><a href="#cb9-336" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb9-337"><a href="#cb9-337" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-338"><a href="#cb9-338" aria-hidden="true" tabindex="-1"></a><span class="fu">## Challenge exercise</span></span>
<span id="cb9-339"><a href="#cb9-339" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-340"><a href="#cb9-340" aria-hidden="true" tabindex="-1"></a>🟠 **Intermediate**</span>
<span id="cb9-341"><a href="#cb9-341" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-342"><a href="#cb9-342" aria-hidden="true" tabindex="-1"></a>**Challenge:** This archive is 100% digital, so you can't test the gate</span>
<span id="cb9-343"><a href="#cb9-343" aria-hidden="true" tabindex="-1"></a>against a real scanned Utah FORGE page. Instead, write a small function</span>
<span id="cb9-344"><a href="#cb9-344" aria-hidden="true" tabindex="-1"></a>that synthetically corrupts clean text (swap random characters for</span>
<span id="cb9-345"><a href="#cb9-345" aria-hidden="true" tabindex="-1"></a>lookalikes, inject repeated tokens) at increasing severity, and find the</span>
<span id="cb9-346"><a href="#cb9-346" aria-hidden="true" tabindex="-1"></a>corruption level at which <span class="in">`evaluate_ocr_quality()`</span> starts rejecting it.</span>
<span id="cb9-347"><a href="#cb9-347" aria-hidden="true" tabindex="-1"></a>This is a legitimate way to stress-test a quality gate before you ever</span>
<span id="cb9-348"><a href="#cb9-348" aria-hidden="true" tabindex="-1"></a>encounter the real noisy data it's meant to catch.</span>
<span id="cb9-349"><a href="#cb9-349" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-350"><a href="#cb9-350" aria-hidden="true" tabindex="-1"></a><span class="fu">## Key takeaways</span></span>
<span id="cb9-351"><a href="#cb9-351" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-352"><a href="#cb9-352" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>OCR quality gating is cheap, heuristic, and worth running</span>
<span id="cb9-353"><a href="#cb9-353" aria-hidden="true" tabindex="-1"></a>  unconditionally — even an archive that's currently 100% digital may not</span>
<span id="cb9-354"><a href="#cb9-354" aria-hidden="true" tabindex="-1"></a>  stay that way, and the check costs almost nothing on clean text.</span>
<span id="cb9-355"><a href="#cb9-355" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Require multiple independent signals to agree before rejecting a page;</span>
<span id="cb9-356"><a href="#cb9-356" aria-hidden="true" tabindex="-1"></a>  a single heuristic alone produces too many false positives.</span>
<span id="cb9-357"><a href="#cb9-357" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Reject-and-flag-for-review beats silently-index-anyway every time</span>
<span id="cb9-358"><a href="#cb9-358" aria-hidden="true" tabindex="-1"></a>  traceability matters more than completeness.</span>
<span id="cb9-359"><a href="#cb9-359" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-360"><a href="#cb9-360" aria-hidden="true" tabindex="-1"></a><span class="fu">## Repository files</span></span>
<span id="cb9-361"><a href="#cb9-361" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-362"><a href="#cb9-362" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> File <span class="pp">|</span> Purpose <span class="pp">|</span></span>
<span id="cb9-363"><a href="#cb9-363" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---|</span></span>
<span id="cb9-364"><a href="#cb9-364" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`code/chapter_06/ocr_quality_gate.py`</span> <span class="pp">|</span> Simplified OCR quality gate <span class="pp">|</span></span>
<span id="cb9-365"><a href="#cb9-365" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`code/chapter_06/make_scanned_example.py`</span> <span class="pp">|</span> Make an image-only PDF from a real report, then OCR and gate it <span class="pp">|</span></span>
<span id="cb9-366"><a href="#cb9-366" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`DDR_UTAH_FORGE/src/rag_pdf/ocr_quality.py`</span> <span class="pp">|</span> Production quality gate (companion repo — requires DDR_UTAH_FORGE) <span class="pp">|</span></span>
<span id="cb9-367"><a href="#cb9-367" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`DDR_UTAH_FORGE/src/rag_pdf/rotation_handler.py`</span> <span class="pp">|</span> Scan rotation detection (companion repo — requires DDR_UTAH_FORGE) <span class="pp">|</span></span>
<span id="cb9-368"><a href="#cb9-368" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-369"><a href="#cb9-369" aria-hidden="true" tabindex="-1"></a>::: {.callout-caution title="CHECKPOINT — Chapter 6"}</span>
<span id="cb9-370"><a href="#cb9-370" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="va">[x]</span> Recognised when a DDR PDF needs OCR instead of direct extraction</span>
<span id="cb9-371"><a href="#cb9-371" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="va">[x]</span> Made a real scanned-style page from a digital report and recovered its text with OCR</span>
<span id="cb9-372"><a href="#cb9-372" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="va">[x]</span> Explained why raw OCR output can't be trusted without scoring it first</span>
<span id="cb9-373"><a href="#cb9-373" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="va">[x]</span> Built a quality gate that rejects bad text before it reaches the index</span>
<span id="cb9-374"><a href="#cb9-374" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="va">[x]</span> Verified the gate doesn't false-positive on legitimately sparse reports</span>
<span id="cb9-375"><a href="#cb9-375" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb9-376"><a href="#cb9-376" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-377"><a href="#cb9-377" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip .built-box title="✓ WHAT YOU BUILT"}</span>
<span id="cb9-378"><a href="#cb9-378" aria-hidden="true" tabindex="-1"></a>**`ocr_quality_gate.py`** — an OCR quality gate: score any extracted text</span>
<span id="cb9-379"><a href="#cb9-379" aria-hidden="true" tabindex="-1"></a>against four cheap heuristics and decide, automatically, whether it's</span>
<span id="cb9-380"><a href="#cb9-380" aria-hidden="true" tabindex="-1"></a>trustworthy enough to index or needs a human to review it first.</span>
<span id="cb9-381"><a href="#cb9-381" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb9-382"><a href="#cb9-382" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-383"><a href="#cb9-383" aria-hidden="true" tabindex="-1"></a><span class="fu">## What can you do now that you couldn't do before?</span></span>
<span id="cb9-384"><a href="#cb9-384" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-385"><a href="#cb9-385" aria-hidden="true" tabindex="-1"></a>You can tell, automatically, whether a page of extracted or OCR'd text is</span>
<span id="cb9-386"><a href="#cb9-386" aria-hidden="true" tabindex="-1"></a>trustworthy enough to search on — and route the pages that aren't to a</span>
<span id="cb9-387"><a href="#cb9-387" aria-hidden="true" tabindex="-1"></a>human for review, instead of silently indexing garbage alongside good</span>
<span id="cb9-388"><a href="#cb9-388" aria-hidden="true" tabindex="-1"></a>reports.</span>
<span id="cb9-389"><a href="#cb9-389" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-390"><a href="#cb9-390" aria-hidden="true" tabindex="-1"></a><span class="fu">## Suggested next step</span></span>
<span id="cb9-391"><a href="#cb9-391" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-392"><a href="#cb9-392" aria-hidden="true" tabindex="-1"></a>**Coming up in Chapter 7:** Once you trust the text coming out of OCR and</span>
<span id="cb9-393"><a href="#cb9-393" aria-hidden="true" tabindex="-1"></a>digital extraction alike, the next question is how to break it into</span>
<span id="cb9-394"><a href="#cb9-394" aria-hidden="true" tabindex="-1"></a>pieces small enough to embed and retrieve — without cutting a stuck-pipe</span>
<span id="cb9-395"><a href="#cb9-395" aria-hidden="true" tabindex="-1"></a>narrative in half across two chunks. That's Chapter 7.</span>
</code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Building Industrial RAG Systems from Daily Drilling Reports</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/djimrastephane/ddr-rag-book/edit/main/chapters/chapter_06.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/djimrastephane/ddr-rag-book/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>Built with Quarto</p>
</div>
  </div>
</footer>




</body></html>