<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>4&nbsp; Semantic Search – Building Industrial RAG Systems from Daily Drilling Reports</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/chapter_05.html" rel="next">
<link href="../chapters/chapter_03.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-de63f62b328812d8e578a4d74e282472.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-6b6957c917596b414ec0b78690761e87.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-de63f62b328812d8e578a4d74e282472.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-e10d541d56eb9122d05640a0c0a0767f.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-04b3fb33f2a973da1159f90c12b2b682.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../site_libs/bootstrap/bootstrap-e10d541d56eb9122d05640a0c0a0767f.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-sidebar docked quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/chapter_01.html">Part I — Foundations</a></li><li class="breadcrumb-item"><a href="../chapters/chapter_04.html"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Semantic Search</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Building Industrial RAG Systems from Daily Drilling Reports</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/djimrastephane/ddr-rag-book" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <a href="../Building-Industrial-RAG-Systems-from-Daily-Drilling-Reports.pdf" title="Download PDF" class="quarto-navigation-tool px-1" aria-label="Download PDF"><i class="bi bi-file-pdf"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../acknowledgements.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Acknowledgements</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Part 0 — Preparing Your Python Workshop</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapter_00.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Part 0: Preparing Your Python Workshop</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Part I — Foundations</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapter_01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Reading Your First DDR</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapter_02.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Cleaning Operational Text</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapter_03.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Searching DDRs</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapter_04.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Semantic Search</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapter_05.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">First RAG System</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Part II — Industrialising the System</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapter_06.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Scanned Reports and OCR Quality Gates</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapter_07.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Chunking That Respects Report Structure</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapter_08.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Vector Databases at Scale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapter_09.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Hybrid Retrieval and Reranking</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapter_10.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Traceable Answers and Hallucination Mitigation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapter_11.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Evaluating Retrieval Quality</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapter_12.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Sequence Detection: Building Toward Cross-Well Intelligence</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapter_13.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Daily Ingestion: Keeping the System Live</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendix/appendix_a_environment_setup.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Appendix A: Environment Setup</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendix/appendix_a1_jupyter.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Appendix A1: Using Jupyter Notebook</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendix/appendix_a2_vscode.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Appendix A2: Using VS Code</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendix/appendix_a3_pycharm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Appendix A3: Using PyCharm Community</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendix/appendix_a4_positron.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Appendix A4: Using Positron</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendix/appendix_a5_terminal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Appendix A5: Terminal-Only Workflow</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendix/appendix_b_oilfield_glossary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Appendix B: Oilfield Abbreviation Glossary</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#learning-objectives" id="toc-learning-objectives" class="nav-link active" data-scroll-target="#learning-objectives"><span class="header-section-number">4.1</span> Learning objectives</a></li>
  <li><a href="#operational-problem" id="toc-operational-problem" class="nav-link" data-scroll-target="#operational-problem"><span class="header-section-number">4.2</span> Operational Problem</a></li>
  <li><a href="#example-ddr-extract" id="toc-example-ddr-extract" class="nav-link" data-scroll-target="#example-ddr-extract"><span class="header-section-number">4.3</span> Example DDR extract</a></li>
  <li><a href="#theory" id="toc-theory" class="nav-link" data-scroll-target="#theory"><span class="header-section-number">4.4</span> Theory</a></li>
  <li><a href="#implementation" id="toc-implementation" class="nav-link" data-scroll-target="#implementation"><span class="header-section-number">4.5</span> Implementation</a>
  <ul class="collapse">
  <li><a href="#step-1-load-every-reports-text" id="toc-step-1-load-every-reports-text" class="nav-link" data-scroll-target="#step-1-load-every-reports-text"><span class="header-section-number">4.5.1</span> Step 1: load every report’s text</a></li>
  <li><a href="#step-2-convert-text-into-vectors" id="toc-step-2-convert-text-into-vectors" class="nav-link" data-scroll-target="#step-2-convert-text-into-vectors"><span class="header-section-number">4.5.2</span> Step 2: convert text into vectors</a></li>
  <li><a href="#step-3-rank-reports-against-a-query" id="toc-step-3-rank-reports-against-a-query" class="nav-link" data-scroll-target="#step-3-rank-reports-against-a-query"><span class="header-section-number">4.5.3</span> Step 3: rank reports against a query</a></li>
  </ul></li>
  <li><a href="#production-reality" id="toc-production-reality" class="nav-link" data-scroll-target="#production-reality"><span class="header-section-number">4.6</span> Production Reality</a></li>
  <li><a href="#practical-exercise" id="toc-practical-exercise" class="nav-link" data-scroll-target="#practical-exercise"><span class="header-section-number">4.7</span> Practical exercise</a></li>
  <li><a href="#field-notes" id="toc-field-notes" class="nav-link" data-scroll-target="#field-notes"><span class="header-section-number">4.8</span> Field notes</a></li>
  <li><a href="#challenge-exercise" id="toc-challenge-exercise" class="nav-link" data-scroll-target="#challenge-exercise"><span class="header-section-number">4.9</span> Challenge exercise</a></li>
  <li><a href="#key-takeaways" id="toc-key-takeaways" class="nav-link" data-scroll-target="#key-takeaways"><span class="header-section-number">4.10</span> Key takeaways</a></li>
  <li><a href="#repository-files" id="toc-repository-files" class="nav-link" data-scroll-target="#repository-files"><span class="header-section-number">4.11</span> Repository files</a></li>
  <li><a href="#what-can-you-do-now-that-you-couldnt-do-before" id="toc-what-can-you-do-now-that-you-couldnt-do-before" class="nav-link" data-scroll-target="#what-can-you-do-now-that-you-couldnt-do-before"><span class="header-section-number">4.12</span> What can you do now that you couldn’t do before?</a></li>
  <li><a href="#suggested-next-step" id="toc-suggested-next-step" class="nav-link" data-scroll-target="#suggested-next-step"><span class="header-section-number">4.13</span> Suggested next step</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/djimrastephane/ddr-rag-book/edit/main/chapters/chapter_04.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/djimrastephane/ddr-rag-book/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/chapter_01.html">Part I — Foundations</a></li><li class="breadcrumb-item"><a href="../chapters/chapter_04.html"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Semantic Search</span></a></li></ol></nav>
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title"><span id="sec-chapter-04" class="quarto-section-identifier"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Semantic Search</span></span></h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="pipeline-diagram">
<p><img src="../figures/diagrams/pipeline_ch04_light.svg" class="diagram-light img-fluid" width="180"> <img src="../figures/diagrams/pipeline_ch04_dark.svg" class="diagram-dark img-fluid" width="180"></p>
</div>
<div class="chapter-status">
<p>Progress <code>████░░░░░░░░░</code> <strong>4 / 13</strong> &nbsp;·&nbsp; <strong>Estimated time:</strong> 60–75 min &nbsp;·&nbsp; <strong>Difficulty:</strong> 🟠 Intermediate</p>
</div>
<section id="learning-objectives" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="learning-objectives"><span class="header-section-number">4.1</span> Learning objectives</h2>
<p>By the end of this chapter, you will be able to:</p>
<ul>
<li>Explain, without heavy math, what a text embedding is and why nearby vectors mean similar meaning.</li>
<li>Generate embeddings for a folder of DDR text using <code>sentence-transformers</code>.</li>
<li>Retrieve the most semantically similar chunks to a query using cosine similarity, without any exact keyword overlap required.</li>
<li>Recognise that semantic search over whole documents is an improvement, not a complete fix — and that granularity is what actually determines how well it works.</li>
</ul>
</section>
<section id="operational-problem" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="operational-problem"><span class="header-section-number">4.2</span> Operational Problem</h2>
<p>Chapter 3 ended on a real miss: Sarah’s query <code>"stuck pipe"</code> found report #38 (the actual incident) but was blind to report #39, which describes tight hole, high torque, and a decision to pull out of hole — real continued-risk language, written the very next day — without ever using the word “stuck.” Sarah, reading both reports herself, says “yes, obviously, day two of the same problem.” A keyword search can’t see that at all. Let’s find out, honestly, how much of that gap semantic search actually closes.</p>
</section>
<section id="example-ddr-extract" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="example-ddr-extract"><span class="header-section-number">4.3</span> Example DDR extract</h2>
<div class="callout callout-style-default callout-note callout-titled" title="The same query, now by meaning">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>The same query, now by meaning
</div>
</div>
<div class="callout-body-container callout-body">
<pre><code>Query: "stuck pipe"  (same query Chapter 3 used)

Keyword search (Chapter 3): report #39 not in results at all.

Semantic search, whole-report embeddings (this chapter): report #39
  ranks 5th out of 10 — findable, but not prominent. Report #38 (the
  actual incident) ranks 2nd.</code></pre>
</div>
</div>
</section>
<section id="theory" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="theory"><span class="header-section-number">4.4</span> Theory</h2>
<p>An <strong>embedding model</strong> converts a piece of text into a fixed-length vector of numbers — typically a few hundred dimensions — such that texts with similar meaning end up as vectors that are close together in that space. You don’t need to understand the neural network that produces this vector; you need to understand what it gives you: a numeric representation of meaning you can compare with simple arithmetic.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Engineering Translation: Vector / embedding">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Engineering Translation: Vector / embedding
</div>
</div>
<div class="callout-body-container callout-body">
<p>Think of an embedding as GPS coordinates for meaning. Instead of latitude and longitude, it’s a few hundred numbers — but the idea is the same: two sentences with similar meaning end up with “coordinates” close together, the same way two rigs in the same field end up with similar latitude and longitude, even if their names have nothing in common.</p>
</div>
</div>
<p><strong>Cosine similarity</strong> measures the angle between two vectors — 1.0 for identical direction, 0 for unrelated, negative for opposite. It’s the standard way to compare embeddings because it ignores vector <em>length</em> and focuses purely on <em>direction</em>, which is what carries the meaning here.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Engineering Translation: Cosine similarity">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Engineering Translation: Cosine similarity
</div>
</div>
<div class="callout-body-container callout-body">
<p>Cosine similarity is a compass bearing, not a ruler. It asks “which way is this thing pointing?”, not “how big is it?” — so a short sentence and a long paragraph about the same topic can still score as pointing the same direction, the same way two surveys can report the same azimuth regardless of how long each run was.</p>
</div>
</div>
<p>We use <code>sentence-transformers</code> <span class="citation" data-cites="reimers2019sbert">(<a href="../references.html#ref-reimers2019sbert" role="doc-biblioref">Reimers and Gurevych 2019</a>)</span> with a small, fast model (<code>all-MiniLM-L6-v2</code>) — good enough to prove the concept and small enough to run on a laptop CPU. Chapter 8 replaces the brute-force search here with a proper vector database once the archive grows past what fits comfortably in memory.</p>
<div class="pipeline-diagram">
<p><img src="../figures/diagrams/theory_ch04_embed_light.svg" class="diagram-light img-fluid" width="260"> <img src="../figures/diagrams/theory_ch04_embed_dark.svg" class="diagram-dark img-fluid" width="260"></p>
</div>
</section>
<section id="implementation" class="level2" data-number="4.5">
<h2 data-number="4.5" class="anchored" data-anchor-id="implementation"><span class="header-section-number">4.5</span> Implementation</h2>
<section id="step-1-load-every-reports-text" class="level3" data-number="4.5.1">
<h3 data-number="4.5.1" class="anchored" data-anchor-id="step-1-load-every-reports-text"><span class="header-section-number">4.5.1</span> Step 1: load every report’s text</h3>
<p><strong>What problem are we solving?</strong></p>
<p>Get every report’s text into memory, alongside its filename, so we know which score belongs to which report later.</p>
<p><strong>Inputs</strong></p>
<ul>
<li>A folder of cleaned report text, e.g.&nbsp;<code>datasets/ddr_text/</code>.</li>
</ul>
<p><strong>Expected Output</strong></p>
<p>Two matching lists: report filenames, and each report’s full text.</p>
<div id="be2bdf3e" class="cell" data-execution_count="1">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># code/chapter_04/semantic_search.py</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pathlib <span class="im">import</span> Path</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> load_chunks(text_dir: Path) <span class="op">-&gt;</span> <span class="bu">tuple</span>[<span class="bu">list</span>[<span class="bu">str</span>], <span class="bu">list</span>[<span class="bu">str</span>]]:</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>    filenames, texts <span class="op">=</span> [], []</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> path <span class="kw">in</span> <span class="bu">sorted</span>(text_dir.glob(<span class="st">"*.txt"</span>)):</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>        filenames.append(path.name)</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>        texts.append(path.read_text(encoding<span class="op">=</span><span class="st">"utf-8"</span>))</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> filenames, texts</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>What just happened?</strong></p>
<p>Nothing about meaning yet — this just reads every text file into memory and keeps a matching list of filenames, so that whatever score we calculate next can be traced back to the report it came from.</p>
<p>Note the folder: <code>datasets/ddr_text/</code>, Chapter 1’s raw extraction — <em>not</em> Chapter 2’s <code>datasets/ddr_text_expanded/</code>. That’s deliberate, and the Field Notes at the end of this chapter measure exactly why.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Engineering Translation: Chunk">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Engineering Translation: Chunk
</div>
</div>
<div class="callout-body-container callout-body">
<p>A <strong>chunk</strong> is a piece of text searched as one unit. For now, each whole report is one chunk — <code>load_chunks()</code> above loads one chunk per report. This chapter’s own Field Notes show why that’s too coarse; Chapter 7 splits reports into much smaller chunks to fix it.</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Engineering Translation: Type hints">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Engineering Translation: Type hints
</div>
</div>
<div class="callout-body-container callout-body">
<p>The <code>-&gt; tuple[list[str], list[str]]</code> after the function name looks cryptic but is only a label: it says this function hands back a pair of lists of text strings — the filenames, and the report texts. Python doesn’t enforce it; it’s a note for the next reader and your editor, the same way a valve tag states what flows through without changing the valve. You’ll see these <code>: Path</code> and <code>-&gt; str</code> annotations throughout the book — you can read straight past them without losing the thread.</p>
</div>
</div>
</section>
<section id="step-2-convert-text-into-vectors" class="level3" data-number="4.5.2">
<h3 data-number="4.5.2" class="anchored" data-anchor-id="step-2-convert-text-into-vectors"><span class="header-section-number">4.5.2</span> Step 2: convert text into vectors</h3>
<p><strong>What problem are we solving?</strong></p>
<p>Turn each report’s text into a numeric representation of its meaning, so that “similar meaning” can be measured with arithmetic instead of exact word matching.</p>
<p><strong>Inputs</strong></p>
<ul>
<li><code>MODEL_NAME = "all-MiniLM-L6-v2"</code>, a pre-trained embedding model.</li>
<li>The list of report texts from Step 1.</li>
</ul>
<p><strong>Expected Output</strong></p>
<p>One 384-number vector per report, all packed into a single array.</p>
<div id="91c164fb" class="cell" data-execution_count="2">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sentence_transformers <span class="im">import</span> SentenceTransformer</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>MODEL_NAME <span class="op">=</span> <span class="st">"all-MiniLM-L6-v2"</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> embed_texts(model: SentenceTransformer, texts: <span class="bu">list</span>[<span class="bu">str</span>]) <span class="op">-&gt;</span> np.ndarray:</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>    embeddings <span class="op">=</span> model.encode(texts, normalize_embeddings<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> np.asarray(embeddings)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>What just happened?</strong></p>
<p>The model read each report and produced its “GPS coordinates for meaning” — one vector per report. <code>normalize_embeddings=True</code> scales every vector to the same length, so later we can compare direction only, which is exactly what cosine similarity needs.</p>
</section>
<section id="step-3-rank-reports-against-a-query" class="level3" data-number="4.5.3">
<h3 data-number="4.5.3" class="anchored" data-anchor-id="step-3-rank-reports-against-a-query"><span class="header-section-number">4.5.3</span> Step 3: rank reports against a query</h3>
<p><strong>What problem are we solving?</strong></p>
<p>Given a query like “stuck pipe,” find which reports are closest in meaning — not which reports contain those exact words.</p>
<p><strong>Inputs</strong></p>
<ul>
<li>The query string.</li>
<li>The array of report vectors from Step 2.</li>
</ul>
<p><strong>Expected Output</strong></p>
<p>A ranked list of <code>(filename, score)</code> pairs, highest similarity first.</p>
<div id="e00dcf88" class="cell" data-execution_count="3">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> search(model: SentenceTransformer, query: <span class="bu">str</span>, filenames: <span class="bu">list</span>[<span class="bu">str</span>],</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>           embeddings: np.ndarray, top_k: <span class="bu">int</span> <span class="op">=</span> <span class="dv">3</span>) <span class="op">-&gt;</span> <span class="bu">list</span>[<span class="bu">tuple</span>[<span class="bu">str</span>, <span class="bu">float</span>]]:</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>    query_vec <span class="op">=</span> model.encode([query], normalize_embeddings<span class="op">=</span><span class="va">True</span>)[<span class="dv">0</span>]</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>    scores <span class="op">=</span> embeddings <span class="op">@</span> query_vec  <span class="co"># cosine similarity, since vectors are normalized</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>    top_indices <span class="op">=</span> np.argsort(<span class="op">-</span>scores)[:top_k]</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> [(filenames[i], <span class="bu">float</span>(scores[i])) <span class="cf">for</span> i <span class="kw">in</span> top_indices]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>What just happened?</strong></p>
<p>The query got turned into its own vector, then compared against every report’s vector at once. Because every vector was normalized to the same length in Step 2, one matrix multiplication (<code>embeddings @ query_vec</code>) gives back the cosine similarity for every report simultaneously — that’s the “arithmetic” that replaces exact word matching.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Engineering Translation: Sorting and list comprehensions">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Engineering Translation: Sorting and list comprehensions
</div>
</div>
<div class="callout-body-container callout-body">
<p>Two lines of shorthand do the ranking. <code>np.argsort(-scores)[:top_k]</code> returns the <em>positions</em> that would put the scores in order — the minus sign flips it to highest-first — and <code>[:top_k]</code> keeps just the first few. Then <code>[(filenames[i], float(scores[i])) for i in top_indices]</code> is a <em>list comprehension</em>: read it left to right as “for each position <code>i</code> in the top list, pair its filename with its score.” It’s a compact way to build a list without writing out a full loop, and it’s a pattern you’ll meet often from here on.</p>
</div>
</div>
<p>Run this against all ten sample reports with <code>query="stuck pipe"</code> and <code>top_k=10</code> (the whole ranking, not just the top few), and you get the real numbers behind the callout above:</p>
<pre><code>1. 0.2416  Completion_003_2021-01-06
2. 0.1978  Drilling_038_2020-11-26   &lt;- the actual stuck-pipe day
3. 0.1713  Drilling_049_2020-12-07
4. 0.1657  Drilling_003_2020-10-22
5. 0.1498  Drilling_039_2020-11-27   &lt;- tight hole / high torque, findable now
6. 0.1406  Drilling_048_2020-12-06
7. 0.1342  Drilling_019_2020-11-07
8. 0.1326  Drilling_037_2020-11-25
9. 0.1319  Drilling_050_2020-12-08
10. 0.1169 Drilling_036_2020-11-24</code></pre>
<p>Report #39 went from <em>absent</em> (Chapter 3) to <em>rank 5 of 10</em> — a real improvement, worth having. But it’s not a clean win: the scores are bunched close together (0.12–0.24), and a busy engineer scanning only the top 2 or 3 results would still miss it.</p>
</section>
</section>
<section id="production-reality" class="level2" data-number="4.6">
<h2 data-number="4.6" class="anchored" data-anchor-id="production-reality"><span class="header-section-number">4.6</span> Production Reality</h2>
<div class="callout callout-style-default callout-tip callout-titled" title="Engineering Translation: API">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Engineering Translation: API
</div>
</div>
<div class="callout-body-container callout-body">
<p>An <strong>API</strong> (Application Programming Interface) is how one piece of software asks another to do something over the network — here, sending your text to a company’s server and getting embeddings back, instead of running the model yourself. “Hosted API” and “local model” are the two options this book keeps contrasting from here on: one runs on someone else’s computer, the other runs on yours.</p>
</div>
</div>
<p>This chapter runs the embedding model locally, on a laptop CPU, against ten short reports. Real deployments hit constraints this setup never sees:</p>
<ul>
<li>some teams call a hosted embedding API instead of running a model locally — which means sending report text, possibly confidential well data, to a third party. That’s a data-governance conversation, not just a technical choice, and it’s worth having before it’s a surprise.</li>
<li>embeddings from two different model versions aren’t comparable — if you re-embed your archive with a newer model, old and new vectors can’t be compared against each other, and everything needs re-embedding together.</li>
<li>embedding a full multi-well archive (thousands of reports, not ten) takes real time and, for hosted APIs, real money — a cost that scales with archive size, not query volume.</li>
<li>a similarity score like 0.24 is only meaningful <em>relative to other scores in the same search</em> — it is not “24% similar” in any absolute sense, and comparing scores across different queries or models is not valid.</li>
</ul>
</section>
<section id="practical-exercise" class="level2" data-number="4.7">
<h2 data-number="4.7" class="anchored" data-anchor-id="practical-exercise"><span class="header-section-number">4.7</span> Practical exercise</h2>
<p>🟢 <strong>Beginner</strong></p>
<p><strong>Try it yourself:</strong> Embed all ten sample DDRs and run <code>search(model, "stuck pipe", filenames, embeddings, top_k=10)</code>.</p>
<p><strong>You’ll know it worked when:</strong> <code>FORGE-16A-78-32_Drilling_039_2020-11-27.txt</code> appears somewhere in your ranked results — unlike Chapter 3, where it didn’t appear at all — even if it isn’t near the top.</p>
</section>
<section id="field-notes" class="level2" data-number="4.8">
<h2 data-number="4.8" class="anchored" data-anchor-id="field-notes"><span class="header-section-number">4.8</span> Field notes</h2>
<div class="callout callout-style-default callout-warning callout-titled" title="🔧 Field notes: why whole-document embeddings are noisy">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>🔧 Field notes: why whole-document embeddings are noisy
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Query:</strong> <code>"stuck pipe"</code>, same as above.</p>
<p><strong>Result:</strong> report #39 ranks 5th of 10 when you embed each <em>entire report</em> as one vector — an improvement over keyword search’s zero, but not a clean fix.</p>
<p><strong>Why:</strong> each report is one page, but that page holds seven distinct data tables (casing, mud, drill bits, pumps, BHA, survey data, consumables) plus the narrative time breakdown. Embedding the whole thing blends a handful of sentences of relevant narrative with a few hundred words of numeric table content. The relevant signal — “Work tight hole… high torque… pull out of hole” — is a small fraction of what actually goes into the vector.</p>
<p>Isolate just the narrative lines instead of the whole report, and the picture changes — though not as cleanly as you might hope:</p>
<pre><code>0.6244  report #38 — "Pipe free"
0.3359  report #38 — "During the slide lost tool face and became
                       assembly became stuck"
0.2402  report #39 — "Due to high torque decision to pull out of hole"
0.2331  report #39 — "Hole drag from 6,050' to 5,901' no issues"
0.2206  report #49 — "Attempted multiple times to set packers"
0.2043  report #36 — "Trip out of hole with BHA #17 core assembly."
        (genuinely unrelated coring operation)
0.2008  report #39 — "Work tight hole at 6,526'."</code></pre>
<p>The two lines that directly describe the stuck-pipe event itself separate clearly from everything else (0.62 and 0.34 vs.&nbsp;everything else under 0.25) — something whole-document embedding couldn’t show at all. But below that, there’s no clean cutoff: report #39’s own <code>"hole drag...no issues"</code> line — a routine trip note, not part of the incident — scores almost as high as its <code>"high torque"</code> line (0.23 vs.&nbsp;0.24), while report #36’s genuinely unrelated coring line (0.20) lands in the same narrow band as report #39’s own <code>"tight hole"</code> line (0.20), the actual precursor to the stuck-pipe event. Shared drilling vocabulary (“hole,” “trip,” “torque”) pulls topically-similar-but-irrelevant lines close to genuinely relevant ones once you’re past the two standout lines.</p>
<p><strong>Lesson:</strong> semantic search doesn’t fail because the <em>technique</em> is wrong — it fails here because the <em>unit of retrieval</em> is too coarse. Line-level granularity narrows the field dramatically, but it doesn’t hand you a clean similarity threshold to filter on — the middle of the ranked list still mixes relevant and irrelevant lines together. This is exactly the problem Chapter 7’s chunking (and later, reranking) works on, and it’s worth remembering the next time a semantic search “isn’t working”: check what’s actually inside each embedded vector before blaming the model — but don’t expect a single score cutoff to solve it either.</p>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled" title="🔧 Field notes: does expanding abbreviations actually help semantic search?">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>🔧 Field notes: does expanding abbreviations actually help semantic search?
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Action:</strong> embed the ten reports twice — once from Chapter 1’s raw text (<code>datasets/ddr_text/</code>), once from Chapter 2’s expanded text (<code>datasets/ddr_text_expanded/</code>) — and compare the same two queries at <code>top_k=3</code>.</p>
<p><strong>Result:</strong></p>
<pre><code>Query "bottom hole assembly":
  raw text:      report #38 ranks 2nd  (0.302)
  expanded text: report #38 ranks 1st  (0.372)   &lt;- BHA now reads in full

Query "stuck pipe":
  raw text:      report #38 ranks 2nd
  expanded text: report #38 ranks 2nd            &lt;- essentially unchanged</code></pre>
<p><strong>Why:</strong> expansion only helps a query whose wording matches a term you actually expanded. <code>"bottom hole assembly"</code> improves because the reports now literally contain that phrase instead of only <code>BHA</code> — so report #38 climbs from 2nd to 1st. <code>"stuck pipe"</code> doesn’t move, because “stuck” was never an abbreviation to begin with.</p>
<p><strong>Lesson:</strong> expansion earns its keep for keyword search (Chapter 3, which matches literal words), but its benefit to <em>semantic</em> search is real yet narrow — confined to queries that happen to use a term you expanded. That narrowness is why this book feeds the raw text to the embedding model from here on, rather than adding a whole pipeline stage the semantic path barely uses. Keyword search keeps using the expanded text; embeddings use the raw. Neither choice is arbitrary, and now you’ve measured why.</p>
</div>
</div>
</section>
<section id="challenge-exercise" class="level2" data-number="4.9">
<h2 data-number="4.9" class="anchored" data-anchor-id="challenge-exercise"><span class="header-section-number">4.9</span> Challenge exercise</h2>
<p>🟠 <strong>Intermediate</strong></p>
<p><strong>Challenge:</strong> Reproduce the Field Notes line-level result yourself. Manually pull three lines of text, verbatim from the source reports — report #39’s <code>"Due to high torque decision to pull out of hole"</code>, report #39’s <code>"Hole drag from 6,050' to 5,901' no issues"</code>, and report #36’s <code>"Trip out of hole with BHA #17 core assembly."</code> (a genuinely unrelated line) — embed just those three strings, and confirm the high-torque line scores highest against <code>"stuck pipe"</code>, report #39’s own hole-drag line scores close behind it, and the genuinely unrelated line trails both by a real margin. A reference solution is in <code>code/chapter_04/challenge/</code>.</p>
</section>
<section id="key-takeaways" class="level2" data-number="4.10">
<h2 data-number="4.10" class="anchored" data-anchor-id="key-takeaways"><span class="header-section-number">4.10</span> Key takeaways</h2>
<ul>
<li>Embeddings represent meaning as geometry: similar meaning, nearby vectors.</li>
<li>Cosine similarity is the standard comparison because it isolates direction (meaning) from magnitude.</li>
<li>Semantic search over whole documents is a real improvement on keyword search — report #39 goes from unfindable to rank 5 of 10 — but “an improvement” and “solved” are different claims. Don’t oversell it.</li>
<li>Granularity is often the actual lever, not the embedding model. The same query, same model, same text — just isolated to individual narrative lines instead of a whole noisy report — turns a middling rank-5 result into a clear, checkable win.</li>
<li>Brute-force cosine search (a matrix multiply) is entirely adequate at ten documents. It stops being adequate well before you reach the full 76-report archive’s scale — that’s Chapter 8’s problem to solve.</li>
</ul>
</section>
<section id="repository-files" class="level2" data-number="4.11">
<h2 data-number="4.11" class="anchored" data-anchor-id="repository-files"><span class="header-section-number">4.11</span> Repository files</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>File</th>
<th>Purpose</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>code/chapter_04/semantic_search.py</code></td>
<td>Embedding generation and brute-force cosine search</td>
</tr>
<tr class="even">
<td><code>notebooks/chapter_04_explore.ipynb</code></td>
<td>Interactive companion notebook</td>
</tr>
</tbody>
</table>
<div class="callout callout-style-default callout-caution callout-titled" title="CHECKPOINT — Chapter 4">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Caution</span>CHECKPOINT — Chapter 4
</div>
</div>
<div class="callout-body-container callout-body">
<ul class="task-list">
<li><label><input type="checkbox" checked="">Explained what a text embedding is without needing the underlying math</label></li>
<li><label><input type="checkbox" checked="">Generated embeddings for a folder of DDR text</label></li>
<li><label><input type="checkbox" checked="">Ranked reports by semantic similarity to a query using cosine similarity</label></li>
<li><label><input type="checkbox" checked="">Diagnosed granularity, not the model, as the real bottleneck</label></li>
</ul>
</div>
</div>
<div class="built-box callout callout-style-default callout-tip callout-titled" title="✓ WHAT YOU BUILT">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>✓ WHAT YOU BUILT
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong><code>semantic_search.py</code></strong> — a brute-force semantic search engine: embed a folder of reports once, then rank any query against them by meaning, not spelling.</p>
</div>
</div>
</section>
<section id="what-can-you-do-now-that-you-couldnt-do-before" class="level2" data-number="4.12">
<h2 data-number="4.12" class="anchored" data-anchor-id="what-can-you-do-now-that-you-couldnt-do-before"><span class="header-section-number">4.12</span> What can you do now that you couldn’t do before?</h2>
<p>You can retrieve relevant report passages by meaning instead of exact wording — finding report #39’s continued-risk language even though it never says “stuck” — and you know precisely why the result isn’t perfect yet: granularity, not the model, is the real bottleneck.</p>
</section>
<section id="suggested-next-step" class="level2" data-number="4.13">
<h2 data-number="4.13" class="anchored" data-anchor-id="suggested-next-step"><span class="header-section-number">4.13</span> Suggested next step</h2>
<p><strong>Coming up in Chapter 5:</strong> You can now retrieve relevant passages by meaning, and you’ve learned the honest limits of doing it at whole-document granularity. Chapter 5 turns retrieval into an answer: given a question, retrieve the right evidence, and generate a response that cites exactly where each claim came from. Chapter 7 comes back to fix the granularity problem directly.</p>


<!-- -->

<div id="refs" class="references csl-bib-body hanging-indent" role="list" style="display: none">
<div id="ref-reimers2019sbert" class="csl-entry" role="listitem">
Reimers, Nils, and Iryna Gurevych. 2019. <span>“Sentence-<span>BERT</span>: Sentence Embeddings Using <span>Siamese BERT</span>-Networks.”</span> <em>Proceedings of the 2019 Conference on Empirical Methods in Natural Language Processing</em>.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapters/chapter_03.html" class="pagination-link" aria-label="Searching DDRs">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Searching DDRs</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapters/chapter_05.html" class="pagination-link" aria-label="First RAG System">
        <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">First RAG System</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb8" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu"># Semantic Search {#sec-chapter-04}</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>::: {.content-visible when-format="html"}</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>::: {.pipeline-diagram}</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="al">![](../figures/diagrams/pipeline_ch04_light.svg)</span>{.diagram-light width="180"}</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a><span class="al">![](../figures/diagrams/pipeline_ch04_dark.svg)</span>{.diagram-dark width="180"}</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>::: {.content-visible when-format="pdf"}</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a><span class="al">![](../figures/diagrams/pipeline_ch04.pdf)</span>{width="180" fig-align="center"}</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>::: {.chapter-status}</span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>Progress <span class="in">`████░░░░░░░░░`</span> **4 / 13** &amp;nbsp;·&amp;nbsp; **Estimated time:** 60–75 min &amp;nbsp;·&amp;nbsp; **Difficulty:** 🟠 Intermediate</span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a><span class="fu">## Learning objectives</span></span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-20"><a href="#cb8-20" aria-hidden="true" tabindex="-1"></a>By the end of this chapter, you will be able to:</span>
<span id="cb8-21"><a href="#cb8-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-22"><a href="#cb8-22" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Explain, without heavy math, what a text embedding is and why nearby</span>
<span id="cb8-23"><a href="#cb8-23" aria-hidden="true" tabindex="-1"></a>  vectors mean similar meaning.</span>
<span id="cb8-24"><a href="#cb8-24" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Generate embeddings for a folder of DDR text using</span>
<span id="cb8-25"><a href="#cb8-25" aria-hidden="true" tabindex="-1"></a>  <span class="in">`sentence-transformers`</span>.</span>
<span id="cb8-26"><a href="#cb8-26" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Retrieve the most semantically similar chunks to a query using cosine</span>
<span id="cb8-27"><a href="#cb8-27" aria-hidden="true" tabindex="-1"></a>  similarity, without any exact keyword overlap required.</span>
<span id="cb8-28"><a href="#cb8-28" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Recognise that semantic search over whole documents is an improvement,</span>
<span id="cb8-29"><a href="#cb8-29" aria-hidden="true" tabindex="-1"></a>  not a complete fix — and that granularity is what actually determines</span>
<span id="cb8-30"><a href="#cb8-30" aria-hidden="true" tabindex="-1"></a>  how well it works.</span>
<span id="cb8-31"><a href="#cb8-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-32"><a href="#cb8-32" aria-hidden="true" tabindex="-1"></a><span class="fu">## Operational Problem</span></span>
<span id="cb8-33"><a href="#cb8-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-34"><a href="#cb8-34" aria-hidden="true" tabindex="-1"></a>Chapter 3 ended on a real miss: Sarah's query <span class="in">`"stuck pipe"`</span> found report</span>
<span id="cb8-35"><a href="#cb8-35" aria-hidden="true" tabindex="-1"></a>#38 (the actual incident) but was blind to report #39, which describes</span>
<span id="cb8-36"><a href="#cb8-36" aria-hidden="true" tabindex="-1"></a>tight hole, high torque, and a decision to pull out of hole — real</span>
<span id="cb8-37"><a href="#cb8-37" aria-hidden="true" tabindex="-1"></a>continued-risk language, written the very next day — without ever using</span>
<span id="cb8-38"><a href="#cb8-38" aria-hidden="true" tabindex="-1"></a>the word "stuck." Sarah, reading both reports herself, says "yes,</span>
<span id="cb8-39"><a href="#cb8-39" aria-hidden="true" tabindex="-1"></a>obviously, day two of the same problem." A keyword search can't see that</span>
<span id="cb8-40"><a href="#cb8-40" aria-hidden="true" tabindex="-1"></a>at all. Let's find out, honestly, how much of that gap semantic search</span>
<span id="cb8-41"><a href="#cb8-41" aria-hidden="true" tabindex="-1"></a>actually closes.</span>
<span id="cb8-42"><a href="#cb8-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-43"><a href="#cb8-43" aria-hidden="true" tabindex="-1"></a><span class="fu">## Example DDR extract</span></span>
<span id="cb8-44"><a href="#cb8-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-45"><a href="#cb8-45" aria-hidden="true" tabindex="-1"></a>::: {.callout-note title="The same query, now by meaning"}</span>
<span id="cb8-46"><a href="#cb8-46" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb8-47"><a href="#cb8-47" aria-hidden="true" tabindex="-1"></a><span class="in">Query: "stuck pipe"  (same query Chapter 3 used)</span></span>
<span id="cb8-48"><a href="#cb8-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-49"><a href="#cb8-49" aria-hidden="true" tabindex="-1"></a><span class="in">Keyword search (Chapter 3): report #39 not in results at all.</span></span>
<span id="cb8-50"><a href="#cb8-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-51"><a href="#cb8-51" aria-hidden="true" tabindex="-1"></a><span class="in">Semantic search, whole-report embeddings (this chapter): report #39</span></span>
<span id="cb8-52"><a href="#cb8-52" aria-hidden="true" tabindex="-1"></a><span class="in">  ranks 5th out of 10 — findable, but not prominent. Report #38 (the</span></span>
<span id="cb8-53"><a href="#cb8-53" aria-hidden="true" tabindex="-1"></a><span class="in">  actual incident) ranks 2nd.</span></span>
<span id="cb8-54"><a href="#cb8-54" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb8-55"><a href="#cb8-55" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb8-56"><a href="#cb8-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-57"><a href="#cb8-57" aria-hidden="true" tabindex="-1"></a><span class="fu">## Theory</span></span>
<span id="cb8-58"><a href="#cb8-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-59"><a href="#cb8-59" aria-hidden="true" tabindex="-1"></a>An **embedding model** converts a piece of text into a fixed-length vector</span>
<span id="cb8-60"><a href="#cb8-60" aria-hidden="true" tabindex="-1"></a>of numbers — typically a few hundred dimensions — such that texts with</span>
<span id="cb8-61"><a href="#cb8-61" aria-hidden="true" tabindex="-1"></a>similar meaning end up as vectors that are close together in that space.</span>
<span id="cb8-62"><a href="#cb8-62" aria-hidden="true" tabindex="-1"></a>You don't need to understand the neural network that produces this vector;</span>
<span id="cb8-63"><a href="#cb8-63" aria-hidden="true" tabindex="-1"></a>you need to understand what it gives you: a numeric representation of</span>
<span id="cb8-64"><a href="#cb8-64" aria-hidden="true" tabindex="-1"></a>meaning you can compare with simple arithmetic.</span>
<span id="cb8-65"><a href="#cb8-65" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-66"><a href="#cb8-66" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip title="Engineering Translation: Vector / embedding"}</span>
<span id="cb8-67"><a href="#cb8-67" aria-hidden="true" tabindex="-1"></a>Think of an embedding as GPS coordinates for meaning. Instead of latitude</span>
<span id="cb8-68"><a href="#cb8-68" aria-hidden="true" tabindex="-1"></a>and longitude, it's a few hundred numbers — but the idea is the same: two</span>
<span id="cb8-69"><a href="#cb8-69" aria-hidden="true" tabindex="-1"></a>sentences with similar meaning end up with "coordinates" close together,</span>
<span id="cb8-70"><a href="#cb8-70" aria-hidden="true" tabindex="-1"></a>the same way two rigs in the same field end up with similar latitude and</span>
<span id="cb8-71"><a href="#cb8-71" aria-hidden="true" tabindex="-1"></a>longitude, even if their names have nothing in common.</span>
<span id="cb8-72"><a href="#cb8-72" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb8-73"><a href="#cb8-73" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-74"><a href="#cb8-74" aria-hidden="true" tabindex="-1"></a>**Cosine similarity** measures the angle between two vectors — 1.0 for</span>
<span id="cb8-75"><a href="#cb8-75" aria-hidden="true" tabindex="-1"></a>identical direction, 0 for unrelated, negative for opposite. It's the</span>
<span id="cb8-76"><a href="#cb8-76" aria-hidden="true" tabindex="-1"></a>standard way to compare embeddings because it ignores vector *length* and</span>
<span id="cb8-77"><a href="#cb8-77" aria-hidden="true" tabindex="-1"></a>focuses purely on *direction*, which is what carries the meaning here.</span>
<span id="cb8-78"><a href="#cb8-78" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-79"><a href="#cb8-79" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip title="Engineering Translation: Cosine similarity"}</span>
<span id="cb8-80"><a href="#cb8-80" aria-hidden="true" tabindex="-1"></a>Cosine similarity is a compass bearing, not a ruler. It asks "which way is</span>
<span id="cb8-81"><a href="#cb8-81" aria-hidden="true" tabindex="-1"></a>this thing pointing?", not "how big is it?" — so a short sentence and a</span>
<span id="cb8-82"><a href="#cb8-82" aria-hidden="true" tabindex="-1"></a>long paragraph about the same topic can still score as pointing the same</span>
<span id="cb8-83"><a href="#cb8-83" aria-hidden="true" tabindex="-1"></a>direction, the same way two surveys can report the same azimuth</span>
<span id="cb8-84"><a href="#cb8-84" aria-hidden="true" tabindex="-1"></a>regardless of how long each run was.</span>
<span id="cb8-85"><a href="#cb8-85" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb8-86"><a href="#cb8-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-87"><a href="#cb8-87" aria-hidden="true" tabindex="-1"></a>We use <span class="in">`sentence-transformers`</span> <span class="co">[</span><span class="ot">@reimers2019sbert</span><span class="co">]</span> with a small, fast</span>
<span id="cb8-88"><a href="#cb8-88" aria-hidden="true" tabindex="-1"></a>model (<span class="in">`all-MiniLM-L6-v2`</span>) — good enough to prove the concept and small</span>
<span id="cb8-89"><a href="#cb8-89" aria-hidden="true" tabindex="-1"></a>enough to run on a laptop CPU. Chapter 8 replaces the brute-force search here</span>
<span id="cb8-90"><a href="#cb8-90" aria-hidden="true" tabindex="-1"></a>with a proper vector database once the archive grows past what fits</span>
<span id="cb8-91"><a href="#cb8-91" aria-hidden="true" tabindex="-1"></a>comfortably in memory.</span>
<span id="cb8-92"><a href="#cb8-92" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-93"><a href="#cb8-93" aria-hidden="true" tabindex="-1"></a>::: {.content-visible when-format="html"}</span>
<span id="cb8-94"><a href="#cb8-94" aria-hidden="true" tabindex="-1"></a>::: {.pipeline-diagram}</span>
<span id="cb8-95"><a href="#cb8-95" aria-hidden="true" tabindex="-1"></a><span class="al">![](../figures/diagrams/theory_ch04_embed_light.svg)</span>{.diagram-light width="260"}</span>
<span id="cb8-96"><a href="#cb8-96" aria-hidden="true" tabindex="-1"></a><span class="al">![](../figures/diagrams/theory_ch04_embed_dark.svg)</span>{.diagram-dark width="260"}</span>
<span id="cb8-97"><a href="#cb8-97" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb8-98"><a href="#cb8-98" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb8-99"><a href="#cb8-99" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-100"><a href="#cb8-100" aria-hidden="true" tabindex="-1"></a>::: {.content-visible when-format="pdf"}</span>
<span id="cb8-101"><a href="#cb8-101" aria-hidden="true" tabindex="-1"></a><span class="al">![](../figures/diagrams/theory_ch04_embed.pdf)</span>{width="260" fig-align="center"}</span>
<span id="cb8-102"><a href="#cb8-102" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb8-103"><a href="#cb8-103" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-104"><a href="#cb8-104" aria-hidden="true" tabindex="-1"></a><span class="fu">## Implementation</span></span>
<span id="cb8-105"><a href="#cb8-105" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-106"><a href="#cb8-106" aria-hidden="true" tabindex="-1"></a><span class="fu">### Step 1: load every report's text</span></span>
<span id="cb8-107"><a href="#cb8-107" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-108"><a href="#cb8-108" aria-hidden="true" tabindex="-1"></a>**What problem are we solving?**</span>
<span id="cb8-109"><a href="#cb8-109" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-110"><a href="#cb8-110" aria-hidden="true" tabindex="-1"></a>Get every report's text into memory, alongside its filename, so we know</span>
<span id="cb8-111"><a href="#cb8-111" aria-hidden="true" tabindex="-1"></a>which score belongs to which report later.</span>
<span id="cb8-112"><a href="#cb8-112" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-113"><a href="#cb8-113" aria-hidden="true" tabindex="-1"></a>**Inputs**</span>
<span id="cb8-114"><a href="#cb8-114" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-115"><a href="#cb8-115" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>A folder of cleaned report text, e.g. <span class="in">`datasets/ddr_text/`</span>.</span>
<span id="cb8-116"><a href="#cb8-116" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-117"><a href="#cb8-117" aria-hidden="true" tabindex="-1"></a>**Expected Output**</span>
<span id="cb8-118"><a href="#cb8-118" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-119"><a href="#cb8-119" aria-hidden="true" tabindex="-1"></a>Two matching lists: report filenames, and each report's full text.</span>
<span id="cb8-120"><a href="#cb8-120" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-123"><a href="#cb8-123" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb8-124"><a href="#cb8-124" aria-hidden="true" tabindex="-1"></a><span class="co">#| eval: false</span></span>
<span id="cb8-125"><a href="#cb8-125" aria-hidden="true" tabindex="-1"></a><span class="co"># code/chapter_04/semantic_search.py</span></span>
<span id="cb8-126"><a href="#cb8-126" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pathlib <span class="im">import</span> Path</span>
<span id="cb8-127"><a href="#cb8-127" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-128"><a href="#cb8-128" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> load_chunks(text_dir: Path) <span class="op">-&gt;</span> <span class="bu">tuple</span>[<span class="bu">list</span>[<span class="bu">str</span>], <span class="bu">list</span>[<span class="bu">str</span>]]:</span>
<span id="cb8-129"><a href="#cb8-129" aria-hidden="true" tabindex="-1"></a>    filenames, texts <span class="op">=</span> [], []</span>
<span id="cb8-130"><a href="#cb8-130" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> path <span class="kw">in</span> <span class="bu">sorted</span>(text_dir.glob(<span class="st">"*.txt"</span>)):</span>
<span id="cb8-131"><a href="#cb8-131" aria-hidden="true" tabindex="-1"></a>        filenames.append(path.name)</span>
<span id="cb8-132"><a href="#cb8-132" aria-hidden="true" tabindex="-1"></a>        texts.append(path.read_text(encoding<span class="op">=</span><span class="st">"utf-8"</span>))</span>
<span id="cb8-133"><a href="#cb8-133" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> filenames, texts</span>
<span id="cb8-134"><a href="#cb8-134" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb8-135"><a href="#cb8-135" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-136"><a href="#cb8-136" aria-hidden="true" tabindex="-1"></a>**What just happened?**</span>
<span id="cb8-137"><a href="#cb8-137" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-138"><a href="#cb8-138" aria-hidden="true" tabindex="-1"></a>Nothing about meaning yet — this just reads every text file into memory</span>
<span id="cb8-139"><a href="#cb8-139" aria-hidden="true" tabindex="-1"></a>and keeps a matching list of filenames, so that whatever score we</span>
<span id="cb8-140"><a href="#cb8-140" aria-hidden="true" tabindex="-1"></a>calculate next can be traced back to the report it came from.</span>
<span id="cb8-141"><a href="#cb8-141" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-142"><a href="#cb8-142" aria-hidden="true" tabindex="-1"></a>Note the folder: <span class="in">`datasets/ddr_text/`</span>, Chapter 1's raw extraction — *not*</span>
<span id="cb8-143"><a href="#cb8-143" aria-hidden="true" tabindex="-1"></a>Chapter 2's <span class="in">`datasets/ddr_text_expanded/`</span>. That's deliberate, and the</span>
<span id="cb8-144"><a href="#cb8-144" aria-hidden="true" tabindex="-1"></a>Field Notes at the end of this chapter measure exactly why.</span>
<span id="cb8-145"><a href="#cb8-145" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-146"><a href="#cb8-146" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip title="Engineering Translation: Chunk"}</span>
<span id="cb8-147"><a href="#cb8-147" aria-hidden="true" tabindex="-1"></a>A **chunk** is a piece of text searched as one unit. For now, each whole</span>
<span id="cb8-148"><a href="#cb8-148" aria-hidden="true" tabindex="-1"></a>report is one chunk — <span class="in">`load_chunks()`</span> above loads one chunk per report.</span>
<span id="cb8-149"><a href="#cb8-149" aria-hidden="true" tabindex="-1"></a>This chapter's own Field Notes show why that's too coarse; Chapter 7</span>
<span id="cb8-150"><a href="#cb8-150" aria-hidden="true" tabindex="-1"></a>splits reports into much smaller chunks to fix it.</span>
<span id="cb8-151"><a href="#cb8-151" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb8-152"><a href="#cb8-152" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-153"><a href="#cb8-153" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip title="Engineering Translation: Type hints"}</span>
<span id="cb8-154"><a href="#cb8-154" aria-hidden="true" tabindex="-1"></a>The <span class="in">`-&gt; tuple[list[str], list[str]]`</span> after the function name looks</span>
<span id="cb8-155"><a href="#cb8-155" aria-hidden="true" tabindex="-1"></a>cryptic but is only a label: it says this function hands back a pair of</span>
<span id="cb8-156"><a href="#cb8-156" aria-hidden="true" tabindex="-1"></a>lists of text strings — the filenames, and the report texts. Python</span>
<span id="cb8-157"><a href="#cb8-157" aria-hidden="true" tabindex="-1"></a>doesn't enforce it; it's a note for the next reader and your editor, the</span>
<span id="cb8-158"><a href="#cb8-158" aria-hidden="true" tabindex="-1"></a>same way a valve tag states what flows through without changing the</span>
<span id="cb8-159"><a href="#cb8-159" aria-hidden="true" tabindex="-1"></a>valve. You'll see these <span class="in">`: Path`</span> and <span class="in">`-&gt; str`</span> annotations throughout the</span>
<span id="cb8-160"><a href="#cb8-160" aria-hidden="true" tabindex="-1"></a>book — you can read straight past them without losing the thread.</span>
<span id="cb8-161"><a href="#cb8-161" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb8-162"><a href="#cb8-162" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-163"><a href="#cb8-163" aria-hidden="true" tabindex="-1"></a><span class="fu">### Step 2: convert text into vectors</span></span>
<span id="cb8-164"><a href="#cb8-164" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-165"><a href="#cb8-165" aria-hidden="true" tabindex="-1"></a>**What problem are we solving?**</span>
<span id="cb8-166"><a href="#cb8-166" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-167"><a href="#cb8-167" aria-hidden="true" tabindex="-1"></a>Turn each report's text into a numeric representation of its meaning, so</span>
<span id="cb8-168"><a href="#cb8-168" aria-hidden="true" tabindex="-1"></a>that "similar meaning" can be measured with arithmetic instead of exact</span>
<span id="cb8-169"><a href="#cb8-169" aria-hidden="true" tabindex="-1"></a>word matching.</span>
<span id="cb8-170"><a href="#cb8-170" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-171"><a href="#cb8-171" aria-hidden="true" tabindex="-1"></a>**Inputs**</span>
<span id="cb8-172"><a href="#cb8-172" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-173"><a href="#cb8-173" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="in">`MODEL_NAME = "all-MiniLM-L6-v2"`</span>, a pre-trained embedding model.</span>
<span id="cb8-174"><a href="#cb8-174" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>The list of report texts from Step 1.</span>
<span id="cb8-175"><a href="#cb8-175" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-176"><a href="#cb8-176" aria-hidden="true" tabindex="-1"></a>**Expected Output**</span>
<span id="cb8-177"><a href="#cb8-177" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-178"><a href="#cb8-178" aria-hidden="true" tabindex="-1"></a>One 384-number vector per report, all packed into a single array.</span>
<span id="cb8-179"><a href="#cb8-179" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-182"><a href="#cb8-182" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb8-183"><a href="#cb8-183" aria-hidden="true" tabindex="-1"></a><span class="co">#| eval: false</span></span>
<span id="cb8-184"><a href="#cb8-184" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb8-185"><a href="#cb8-185" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sentence_transformers <span class="im">import</span> SentenceTransformer</span>
<span id="cb8-186"><a href="#cb8-186" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-187"><a href="#cb8-187" aria-hidden="true" tabindex="-1"></a>MODEL_NAME <span class="op">=</span> <span class="st">"all-MiniLM-L6-v2"</span></span>
<span id="cb8-188"><a href="#cb8-188" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-189"><a href="#cb8-189" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> embed_texts(model: SentenceTransformer, texts: <span class="bu">list</span>[<span class="bu">str</span>]) <span class="op">-&gt;</span> np.ndarray:</span>
<span id="cb8-190"><a href="#cb8-190" aria-hidden="true" tabindex="-1"></a>    embeddings <span class="op">=</span> model.encode(texts, normalize_embeddings<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb8-191"><a href="#cb8-191" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> np.asarray(embeddings)</span>
<span id="cb8-192"><a href="#cb8-192" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb8-193"><a href="#cb8-193" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-194"><a href="#cb8-194" aria-hidden="true" tabindex="-1"></a>**What just happened?**</span>
<span id="cb8-195"><a href="#cb8-195" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-196"><a href="#cb8-196" aria-hidden="true" tabindex="-1"></a>The model read each report and produced its "GPS coordinates for</span>
<span id="cb8-197"><a href="#cb8-197" aria-hidden="true" tabindex="-1"></a>meaning" — one vector per report. <span class="in">`normalize_embeddings=True`</span> scales</span>
<span id="cb8-198"><a href="#cb8-198" aria-hidden="true" tabindex="-1"></a>every vector to the same length, so later we can compare direction only,</span>
<span id="cb8-199"><a href="#cb8-199" aria-hidden="true" tabindex="-1"></a>which is exactly what cosine similarity needs.</span>
<span id="cb8-200"><a href="#cb8-200" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-201"><a href="#cb8-201" aria-hidden="true" tabindex="-1"></a><span class="fu">### Step 3: rank reports against a query</span></span>
<span id="cb8-202"><a href="#cb8-202" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-203"><a href="#cb8-203" aria-hidden="true" tabindex="-1"></a>**What problem are we solving?**</span>
<span id="cb8-204"><a href="#cb8-204" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-205"><a href="#cb8-205" aria-hidden="true" tabindex="-1"></a>Given a query like "stuck pipe," find which reports are closest in</span>
<span id="cb8-206"><a href="#cb8-206" aria-hidden="true" tabindex="-1"></a>meaning — not which reports contain those exact words.</span>
<span id="cb8-207"><a href="#cb8-207" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-208"><a href="#cb8-208" aria-hidden="true" tabindex="-1"></a>**Inputs**</span>
<span id="cb8-209"><a href="#cb8-209" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-210"><a href="#cb8-210" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>The query string.</span>
<span id="cb8-211"><a href="#cb8-211" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>The array of report vectors from Step 2.</span>
<span id="cb8-212"><a href="#cb8-212" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-213"><a href="#cb8-213" aria-hidden="true" tabindex="-1"></a>**Expected Output**</span>
<span id="cb8-214"><a href="#cb8-214" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-215"><a href="#cb8-215" aria-hidden="true" tabindex="-1"></a>A ranked list of <span class="in">`(filename, score)`</span> pairs, highest similarity first.</span>
<span id="cb8-216"><a href="#cb8-216" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-219"><a href="#cb8-219" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb8-220"><a href="#cb8-220" aria-hidden="true" tabindex="-1"></a><span class="co">#| eval: false</span></span>
<span id="cb8-221"><a href="#cb8-221" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> search(model: SentenceTransformer, query: <span class="bu">str</span>, filenames: <span class="bu">list</span>[<span class="bu">str</span>],</span>
<span id="cb8-222"><a href="#cb8-222" aria-hidden="true" tabindex="-1"></a>           embeddings: np.ndarray, top_k: <span class="bu">int</span> <span class="op">=</span> <span class="dv">3</span>) <span class="op">-&gt;</span> <span class="bu">list</span>[<span class="bu">tuple</span>[<span class="bu">str</span>, <span class="bu">float</span>]]:</span>
<span id="cb8-223"><a href="#cb8-223" aria-hidden="true" tabindex="-1"></a>    query_vec <span class="op">=</span> model.encode([query], normalize_embeddings<span class="op">=</span><span class="va">True</span>)[<span class="dv">0</span>]</span>
<span id="cb8-224"><a href="#cb8-224" aria-hidden="true" tabindex="-1"></a>    scores <span class="op">=</span> embeddings <span class="op">@</span> query_vec  <span class="co"># cosine similarity, since vectors are normalized</span></span>
<span id="cb8-225"><a href="#cb8-225" aria-hidden="true" tabindex="-1"></a>    top_indices <span class="op">=</span> np.argsort(<span class="op">-</span>scores)[:top_k]</span>
<span id="cb8-226"><a href="#cb8-226" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> [(filenames[i], <span class="bu">float</span>(scores[i])) <span class="cf">for</span> i <span class="kw">in</span> top_indices]</span>
<span id="cb8-227"><a href="#cb8-227" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb8-228"><a href="#cb8-228" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-229"><a href="#cb8-229" aria-hidden="true" tabindex="-1"></a>**What just happened?**</span>
<span id="cb8-230"><a href="#cb8-230" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-231"><a href="#cb8-231" aria-hidden="true" tabindex="-1"></a>The query got turned into its own vector, then compared against every</span>
<span id="cb8-232"><a href="#cb8-232" aria-hidden="true" tabindex="-1"></a>report's vector at once. Because every vector was normalized to the same</span>
<span id="cb8-233"><a href="#cb8-233" aria-hidden="true" tabindex="-1"></a>length in Step 2, one matrix multiplication (<span class="in">`embeddings @ query_vec`</span>)</span>
<span id="cb8-234"><a href="#cb8-234" aria-hidden="true" tabindex="-1"></a>gives back the cosine similarity for every report simultaneously —</span>
<span id="cb8-235"><a href="#cb8-235" aria-hidden="true" tabindex="-1"></a>that's the "arithmetic" that replaces exact word matching.</span>
<span id="cb8-236"><a href="#cb8-236" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-237"><a href="#cb8-237" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip title="Engineering Translation: Sorting and list comprehensions"}</span>
<span id="cb8-238"><a href="#cb8-238" aria-hidden="true" tabindex="-1"></a>Two lines of shorthand do the ranking. <span class="in">`np.argsort(-scores)[:top_k]`</span></span>
<span id="cb8-239"><a href="#cb8-239" aria-hidden="true" tabindex="-1"></a>returns the *positions* that would put the scores in order — the minus</span>
<span id="cb8-240"><a href="#cb8-240" aria-hidden="true" tabindex="-1"></a>sign flips it to highest-first — and <span class="in">`[:top_k]`</span> keeps just the first few.</span>
<span id="cb8-241"><a href="#cb8-241" aria-hidden="true" tabindex="-1"></a>Then <span class="in">`[(filenames[i], float(scores[i])) for i in top_indices]`</span> is a *list</span>
<span id="cb8-242"><a href="#cb8-242" aria-hidden="true" tabindex="-1"></a>comprehension*: read it left to right as "for each position <span class="in">`i`</span> in the</span>
<span id="cb8-243"><a href="#cb8-243" aria-hidden="true" tabindex="-1"></a>top list, pair its filename with its score." It's a compact way to build</span>
<span id="cb8-244"><a href="#cb8-244" aria-hidden="true" tabindex="-1"></a>a list without writing out a full loop, and it's a pattern you'll meet</span>
<span id="cb8-245"><a href="#cb8-245" aria-hidden="true" tabindex="-1"></a>often from here on.</span>
<span id="cb8-246"><a href="#cb8-246" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb8-247"><a href="#cb8-247" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-248"><a href="#cb8-248" aria-hidden="true" tabindex="-1"></a>Run this against all ten sample reports with <span class="in">`query="stuck pipe"`</span> and</span>
<span id="cb8-249"><a href="#cb8-249" aria-hidden="true" tabindex="-1"></a><span class="in">`top_k=10`</span> (the whole ranking, not just the top few), and you get the</span>
<span id="cb8-250"><a href="#cb8-250" aria-hidden="true" tabindex="-1"></a>real numbers behind the callout above:</span>
<span id="cb8-251"><a href="#cb8-251" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-252"><a href="#cb8-252" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb8-253"><a href="#cb8-253" aria-hidden="true" tabindex="-1"></a><span class="in">1. 0.2416  Completion_003_2021-01-06</span></span>
<span id="cb8-254"><a href="#cb8-254" aria-hidden="true" tabindex="-1"></a><span class="in">2. 0.1978  Drilling_038_2020-11-26   &lt;- the actual stuck-pipe day</span></span>
<span id="cb8-255"><a href="#cb8-255" aria-hidden="true" tabindex="-1"></a><span class="in">3. 0.1713  Drilling_049_2020-12-07</span></span>
<span id="cb8-256"><a href="#cb8-256" aria-hidden="true" tabindex="-1"></a><span class="in">4. 0.1657  Drilling_003_2020-10-22</span></span>
<span id="cb8-257"><a href="#cb8-257" aria-hidden="true" tabindex="-1"></a><span class="in">5. 0.1498  Drilling_039_2020-11-27   &lt;- tight hole / high torque, findable now</span></span>
<span id="cb8-258"><a href="#cb8-258" aria-hidden="true" tabindex="-1"></a><span class="in">6. 0.1406  Drilling_048_2020-12-06</span></span>
<span id="cb8-259"><a href="#cb8-259" aria-hidden="true" tabindex="-1"></a><span class="in">7. 0.1342  Drilling_019_2020-11-07</span></span>
<span id="cb8-260"><a href="#cb8-260" aria-hidden="true" tabindex="-1"></a><span class="in">8. 0.1326  Drilling_037_2020-11-25</span></span>
<span id="cb8-261"><a href="#cb8-261" aria-hidden="true" tabindex="-1"></a><span class="in">9. 0.1319  Drilling_050_2020-12-08</span></span>
<span id="cb8-262"><a href="#cb8-262" aria-hidden="true" tabindex="-1"></a><span class="in">10. 0.1169 Drilling_036_2020-11-24</span></span>
<span id="cb8-263"><a href="#cb8-263" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb8-264"><a href="#cb8-264" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-265"><a href="#cb8-265" aria-hidden="true" tabindex="-1"></a>Report #39 went from *absent* (Chapter 3) to *rank 5 of 10* — a real</span>
<span id="cb8-266"><a href="#cb8-266" aria-hidden="true" tabindex="-1"></a>improvement, worth having. But it's not a clean win: the scores are</span>
<span id="cb8-267"><a href="#cb8-267" aria-hidden="true" tabindex="-1"></a>bunched close together (0.12–0.24), and a busy engineer scanning only the</span>
<span id="cb8-268"><a href="#cb8-268" aria-hidden="true" tabindex="-1"></a>top 2 or 3 results would still miss it.</span>
<span id="cb8-269"><a href="#cb8-269" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-270"><a href="#cb8-270" aria-hidden="true" tabindex="-1"></a><span class="fu">## Production Reality</span></span>
<span id="cb8-271"><a href="#cb8-271" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-272"><a href="#cb8-272" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip title="Engineering Translation: API"}</span>
<span id="cb8-273"><a href="#cb8-273" aria-hidden="true" tabindex="-1"></a>An **API** (Application Programming Interface) is how one piece of</span>
<span id="cb8-274"><a href="#cb8-274" aria-hidden="true" tabindex="-1"></a>software asks another to do something over the network — here, sending</span>
<span id="cb8-275"><a href="#cb8-275" aria-hidden="true" tabindex="-1"></a>your text to a company's server and getting embeddings back, instead of</span>
<span id="cb8-276"><a href="#cb8-276" aria-hidden="true" tabindex="-1"></a>running the model yourself. "Hosted API" and "local model" are the two</span>
<span id="cb8-277"><a href="#cb8-277" aria-hidden="true" tabindex="-1"></a>options this book keeps contrasting from here on: one runs on someone</span>
<span id="cb8-278"><a href="#cb8-278" aria-hidden="true" tabindex="-1"></a>else's computer, the other runs on yours.</span>
<span id="cb8-279"><a href="#cb8-279" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb8-280"><a href="#cb8-280" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-281"><a href="#cb8-281" aria-hidden="true" tabindex="-1"></a>This chapter runs the embedding model locally, on a laptop CPU, against</span>
<span id="cb8-282"><a href="#cb8-282" aria-hidden="true" tabindex="-1"></a>ten short reports. Real deployments hit constraints this setup never</span>
<span id="cb8-283"><a href="#cb8-283" aria-hidden="true" tabindex="-1"></a>sees:</span>
<span id="cb8-284"><a href="#cb8-284" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-285"><a href="#cb8-285" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>some teams call a hosted embedding API instead of running a model</span>
<span id="cb8-286"><a href="#cb8-286" aria-hidden="true" tabindex="-1"></a>  locally — which means sending report text, possibly confidential well</span>
<span id="cb8-287"><a href="#cb8-287" aria-hidden="true" tabindex="-1"></a>  data, to a third party. That's a data-governance conversation, not just</span>
<span id="cb8-288"><a href="#cb8-288" aria-hidden="true" tabindex="-1"></a>  a technical choice, and it's worth having before it's a surprise.</span>
<span id="cb8-289"><a href="#cb8-289" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>embeddings from two different model versions aren't comparable — if you</span>
<span id="cb8-290"><a href="#cb8-290" aria-hidden="true" tabindex="-1"></a>  re-embed your archive with a newer model, old and new vectors can't be</span>
<span id="cb8-291"><a href="#cb8-291" aria-hidden="true" tabindex="-1"></a>  compared against each other, and everything needs re-embedding together.</span>
<span id="cb8-292"><a href="#cb8-292" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>embedding a full multi-well archive (thousands of reports, not ten)</span>
<span id="cb8-293"><a href="#cb8-293" aria-hidden="true" tabindex="-1"></a>  takes real time and, for hosted APIs, real money — a cost that scales</span>
<span id="cb8-294"><a href="#cb8-294" aria-hidden="true" tabindex="-1"></a>  with archive size, not query volume.</span>
<span id="cb8-295"><a href="#cb8-295" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>a similarity score like 0.24 is only meaningful *relative to other</span>
<span id="cb8-296"><a href="#cb8-296" aria-hidden="true" tabindex="-1"></a>  scores in the same search* — it is not "24% similar" in any absolute</span>
<span id="cb8-297"><a href="#cb8-297" aria-hidden="true" tabindex="-1"></a>  sense, and comparing scores across different queries or models is not</span>
<span id="cb8-298"><a href="#cb8-298" aria-hidden="true" tabindex="-1"></a>  valid.</span>
<span id="cb8-299"><a href="#cb8-299" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-300"><a href="#cb8-300" aria-hidden="true" tabindex="-1"></a><span class="fu">## Practical exercise</span></span>
<span id="cb8-301"><a href="#cb8-301" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-302"><a href="#cb8-302" aria-hidden="true" tabindex="-1"></a>🟢 **Beginner**</span>
<span id="cb8-303"><a href="#cb8-303" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-304"><a href="#cb8-304" aria-hidden="true" tabindex="-1"></a>**Try it yourself:** Embed all ten sample DDRs and run</span>
<span id="cb8-305"><a href="#cb8-305" aria-hidden="true" tabindex="-1"></a><span class="in">`search(model, "stuck pipe", filenames, embeddings, top_k=10)`</span>.</span>
<span id="cb8-306"><a href="#cb8-306" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-307"><a href="#cb8-307" aria-hidden="true" tabindex="-1"></a>**You'll know it worked when:** <span class="in">`FORGE-16A-78-32_Drilling_039_2020-11-27.txt`</span></span>
<span id="cb8-308"><a href="#cb8-308" aria-hidden="true" tabindex="-1"></a>appears somewhere in your ranked results — unlike Chapter 3, where it</span>
<span id="cb8-309"><a href="#cb8-309" aria-hidden="true" tabindex="-1"></a>didn't appear at all — even if it isn't near the top.</span>
<span id="cb8-310"><a href="#cb8-310" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-311"><a href="#cb8-311" aria-hidden="true" tabindex="-1"></a><span class="fu">## Field notes</span></span>
<span id="cb8-312"><a href="#cb8-312" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-313"><a href="#cb8-313" aria-hidden="true" tabindex="-1"></a>::: {.callout-warning title="🔧 Field notes: why whole-document embeddings are noisy"}</span>
<span id="cb8-314"><a href="#cb8-314" aria-hidden="true" tabindex="-1"></a>**Query:** <span class="in">`"stuck pipe"`</span>, same as above.</span>
<span id="cb8-315"><a href="#cb8-315" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-316"><a href="#cb8-316" aria-hidden="true" tabindex="-1"></a>**Result:** report #39 ranks 5th of 10 when you embed each *entire</span>
<span id="cb8-317"><a href="#cb8-317" aria-hidden="true" tabindex="-1"></a>report* as one vector — an improvement over keyword search's zero, but</span>
<span id="cb8-318"><a href="#cb8-318" aria-hidden="true" tabindex="-1"></a>not a clean fix.</span>
<span id="cb8-319"><a href="#cb8-319" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-320"><a href="#cb8-320" aria-hidden="true" tabindex="-1"></a>**Why:** each report is one page, but that page holds seven distinct data</span>
<span id="cb8-321"><a href="#cb8-321" aria-hidden="true" tabindex="-1"></a>tables (casing, mud, drill bits, pumps, BHA, survey data, consumables)</span>
<span id="cb8-322"><a href="#cb8-322" aria-hidden="true" tabindex="-1"></a>plus the narrative time breakdown. Embedding the whole thing blends a</span>
<span id="cb8-323"><a href="#cb8-323" aria-hidden="true" tabindex="-1"></a>handful of sentences of relevant narrative with a few hundred words of</span>
<span id="cb8-324"><a href="#cb8-324" aria-hidden="true" tabindex="-1"></a>numeric table content. The relevant signal — "Work tight hole... high</span>
<span id="cb8-325"><a href="#cb8-325" aria-hidden="true" tabindex="-1"></a>torque... pull out of hole" — is a small fraction of what actually goes</span>
<span id="cb8-326"><a href="#cb8-326" aria-hidden="true" tabindex="-1"></a>into the vector.</span>
<span id="cb8-327"><a href="#cb8-327" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-328"><a href="#cb8-328" aria-hidden="true" tabindex="-1"></a>Isolate just the narrative lines instead of the whole report, and the</span>
<span id="cb8-329"><a href="#cb8-329" aria-hidden="true" tabindex="-1"></a>picture changes — though not as cleanly as you might hope:</span>
<span id="cb8-330"><a href="#cb8-330" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-331"><a href="#cb8-331" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb8-332"><a href="#cb8-332" aria-hidden="true" tabindex="-1"></a><span class="in">0.6244  report #38 — "Pipe free"</span></span>
<span id="cb8-333"><a href="#cb8-333" aria-hidden="true" tabindex="-1"></a><span class="in">0.3359  report #38 — "During the slide lost tool face and became</span></span>
<span id="cb8-334"><a href="#cb8-334" aria-hidden="true" tabindex="-1"></a><span class="in">                       assembly became stuck"</span></span>
<span id="cb8-335"><a href="#cb8-335" aria-hidden="true" tabindex="-1"></a><span class="in">0.2402  report #39 — "Due to high torque decision to pull out of hole"</span></span>
<span id="cb8-336"><a href="#cb8-336" aria-hidden="true" tabindex="-1"></a><span class="in">0.2331  report #39 — "Hole drag from 6,050' to 5,901' no issues"</span></span>
<span id="cb8-337"><a href="#cb8-337" aria-hidden="true" tabindex="-1"></a><span class="in">0.2206  report #49 — "Attempted multiple times to set packers"</span></span>
<span id="cb8-338"><a href="#cb8-338" aria-hidden="true" tabindex="-1"></a><span class="in">0.2043  report #36 — "Trip out of hole with BHA #17 core assembly."</span></span>
<span id="cb8-339"><a href="#cb8-339" aria-hidden="true" tabindex="-1"></a><span class="in">        (genuinely unrelated coring operation)</span></span>
<span id="cb8-340"><a href="#cb8-340" aria-hidden="true" tabindex="-1"></a><span class="in">0.2008  report #39 — "Work tight hole at 6,526'."</span></span>
<span id="cb8-341"><a href="#cb8-341" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb8-342"><a href="#cb8-342" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-343"><a href="#cb8-343" aria-hidden="true" tabindex="-1"></a>The two lines that directly describe the stuck-pipe event itself separate</span>
<span id="cb8-344"><a href="#cb8-344" aria-hidden="true" tabindex="-1"></a>clearly from everything else (0.62 and 0.34 vs. everything else under</span>
<span id="cb8-345"><a href="#cb8-345" aria-hidden="true" tabindex="-1"></a>0.25) — something whole-document embedding couldn't show at all. But</span>
<span id="cb8-346"><a href="#cb8-346" aria-hidden="true" tabindex="-1"></a>below that, there's no clean cutoff: report #39's own `"hole drag...no</span>
<span id="cb8-347"><a href="#cb8-347" aria-hidden="true" tabindex="-1"></a>issues"` line — a routine trip note, not part of the incident — scores</span>
<span id="cb8-348"><a href="#cb8-348" aria-hidden="true" tabindex="-1"></a>almost as high as its <span class="in">`"high torque"`</span> line (0.23 vs. 0.24), while report</span>
<span id="cb8-349"><a href="#cb8-349" aria-hidden="true" tabindex="-1"></a>#36's genuinely unrelated coring line (0.20) lands in the same narrow</span>
<span id="cb8-350"><a href="#cb8-350" aria-hidden="true" tabindex="-1"></a>band as report #39's own <span class="in">`"tight hole"`</span> line (0.20), the actual precursor</span>
<span id="cb8-351"><a href="#cb8-351" aria-hidden="true" tabindex="-1"></a>to the stuck-pipe event. Shared drilling vocabulary ("hole," "trip,"</span>
<span id="cb8-352"><a href="#cb8-352" aria-hidden="true" tabindex="-1"></a>"torque") pulls topically-similar-but-irrelevant lines close to</span>
<span id="cb8-353"><a href="#cb8-353" aria-hidden="true" tabindex="-1"></a>genuinely relevant ones once you're past the two standout lines.</span>
<span id="cb8-354"><a href="#cb8-354" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-355"><a href="#cb8-355" aria-hidden="true" tabindex="-1"></a>**Lesson:** semantic search doesn't fail because the *technique* is wrong</span>
<span id="cb8-356"><a href="#cb8-356" aria-hidden="true" tabindex="-1"></a>— it fails here because the *unit of retrieval* is too coarse. Line-level</span>
<span id="cb8-357"><a href="#cb8-357" aria-hidden="true" tabindex="-1"></a>granularity narrows the field dramatically, but it doesn't hand you a</span>
<span id="cb8-358"><a href="#cb8-358" aria-hidden="true" tabindex="-1"></a>clean similarity threshold to filter on — the middle of the ranked list</span>
<span id="cb8-359"><a href="#cb8-359" aria-hidden="true" tabindex="-1"></a>still mixes relevant and irrelevant lines together. This is exactly the</span>
<span id="cb8-360"><a href="#cb8-360" aria-hidden="true" tabindex="-1"></a>problem Chapter 7's chunking (and later, reranking) works on, and it's</span>
<span id="cb8-361"><a href="#cb8-361" aria-hidden="true" tabindex="-1"></a>worth remembering the next time a semantic search "isn't working": check</span>
<span id="cb8-362"><a href="#cb8-362" aria-hidden="true" tabindex="-1"></a>what's actually inside each embedded vector before blaming the model —</span>
<span id="cb8-363"><a href="#cb8-363" aria-hidden="true" tabindex="-1"></a>but don't expect a single score cutoff to solve it either.</span>
<span id="cb8-364"><a href="#cb8-364" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb8-365"><a href="#cb8-365" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-366"><a href="#cb8-366" aria-hidden="true" tabindex="-1"></a>::: {.callout-warning title="🔧 Field notes: does expanding abbreviations actually help semantic search?"}</span>
<span id="cb8-367"><a href="#cb8-367" aria-hidden="true" tabindex="-1"></a>**Action:** embed the ten reports twice — once from Chapter 1's raw text</span>
<span id="cb8-368"><a href="#cb8-368" aria-hidden="true" tabindex="-1"></a>(<span class="in">`datasets/ddr_text/`</span>), once from Chapter 2's expanded text</span>
<span id="cb8-369"><a href="#cb8-369" aria-hidden="true" tabindex="-1"></a>(<span class="in">`datasets/ddr_text_expanded/`</span>) — and compare the same two queries at</span>
<span id="cb8-370"><a href="#cb8-370" aria-hidden="true" tabindex="-1"></a><span class="in">`top_k=3`</span>.</span>
<span id="cb8-371"><a href="#cb8-371" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-372"><a href="#cb8-372" aria-hidden="true" tabindex="-1"></a>**Result:**</span>
<span id="cb8-373"><a href="#cb8-373" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-374"><a href="#cb8-374" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb8-375"><a href="#cb8-375" aria-hidden="true" tabindex="-1"></a><span class="in">Query "bottom hole assembly":</span></span>
<span id="cb8-376"><a href="#cb8-376" aria-hidden="true" tabindex="-1"></a><span class="in">  raw text:      report #38 ranks 2nd  (0.302)</span></span>
<span id="cb8-377"><a href="#cb8-377" aria-hidden="true" tabindex="-1"></a><span class="in">  expanded text: report #38 ranks 1st  (0.372)   &lt;- BHA now reads in full</span></span>
<span id="cb8-378"><a href="#cb8-378" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-379"><a href="#cb8-379" aria-hidden="true" tabindex="-1"></a><span class="in">Query "stuck pipe":</span></span>
<span id="cb8-380"><a href="#cb8-380" aria-hidden="true" tabindex="-1"></a><span class="in">  raw text:      report #38 ranks 2nd</span></span>
<span id="cb8-381"><a href="#cb8-381" aria-hidden="true" tabindex="-1"></a><span class="in">  expanded text: report #38 ranks 2nd            &lt;- essentially unchanged</span></span>
<span id="cb8-382"><a href="#cb8-382" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb8-383"><a href="#cb8-383" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-384"><a href="#cb8-384" aria-hidden="true" tabindex="-1"></a>**Why:** expansion only helps a query whose wording matches a term you</span>
<span id="cb8-385"><a href="#cb8-385" aria-hidden="true" tabindex="-1"></a>actually expanded. <span class="in">`"bottom hole assembly"`</span> improves because the reports</span>
<span id="cb8-386"><a href="#cb8-386" aria-hidden="true" tabindex="-1"></a>now literally contain that phrase instead of only <span class="in">`BHA`</span> — so report #38</span>
<span id="cb8-387"><a href="#cb8-387" aria-hidden="true" tabindex="-1"></a>climbs from 2nd to 1st. <span class="in">`"stuck pipe"`</span> doesn't move, because "stuck" was</span>
<span id="cb8-388"><a href="#cb8-388" aria-hidden="true" tabindex="-1"></a>never an abbreviation to begin with.</span>
<span id="cb8-389"><a href="#cb8-389" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-390"><a href="#cb8-390" aria-hidden="true" tabindex="-1"></a>**Lesson:** expansion earns its keep for keyword search (Chapter 3, which</span>
<span id="cb8-391"><a href="#cb8-391" aria-hidden="true" tabindex="-1"></a>matches literal words), but its benefit to *semantic* search is real yet</span>
<span id="cb8-392"><a href="#cb8-392" aria-hidden="true" tabindex="-1"></a>narrow — confined to queries that happen to use a term you expanded. That</span>
<span id="cb8-393"><a href="#cb8-393" aria-hidden="true" tabindex="-1"></a>narrowness is why this book feeds the raw text to the embedding model from</span>
<span id="cb8-394"><a href="#cb8-394" aria-hidden="true" tabindex="-1"></a>here on, rather than adding a whole pipeline stage the semantic path</span>
<span id="cb8-395"><a href="#cb8-395" aria-hidden="true" tabindex="-1"></a>barely uses. Keyword search keeps using the expanded text; embeddings use</span>
<span id="cb8-396"><a href="#cb8-396" aria-hidden="true" tabindex="-1"></a>the raw. Neither choice is arbitrary, and now you've measured why.</span>
<span id="cb8-397"><a href="#cb8-397" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb8-398"><a href="#cb8-398" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-399"><a href="#cb8-399" aria-hidden="true" tabindex="-1"></a><span class="fu">## Challenge exercise</span></span>
<span id="cb8-400"><a href="#cb8-400" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-401"><a href="#cb8-401" aria-hidden="true" tabindex="-1"></a>🟠 **Intermediate**</span>
<span id="cb8-402"><a href="#cb8-402" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-403"><a href="#cb8-403" aria-hidden="true" tabindex="-1"></a>**Challenge:** Reproduce the Field Notes line-level result yourself.</span>
<span id="cb8-404"><a href="#cb8-404" aria-hidden="true" tabindex="-1"></a>Manually pull three lines of text, verbatim from the source reports —</span>
<span id="cb8-405"><a href="#cb8-405" aria-hidden="true" tabindex="-1"></a>report #39's <span class="in">`"Due to high torque decision to pull out of hole"`</span>, report</span>
<span id="cb8-406"><a href="#cb8-406" aria-hidden="true" tabindex="-1"></a>#39's <span class="in">`"Hole drag from 6,050' to 5,901' no issues"`</span>, and report #36's</span>
<span id="cb8-407"><a href="#cb8-407" aria-hidden="true" tabindex="-1"></a><span class="in">`"Trip out of hole with BHA #17 core assembly."`</span> (a genuinely unrelated</span>
<span id="cb8-408"><a href="#cb8-408" aria-hidden="true" tabindex="-1"></a>line) — embed just those three strings, and confirm the high-torque line</span>
<span id="cb8-409"><a href="#cb8-409" aria-hidden="true" tabindex="-1"></a>scores highest against <span class="in">`"stuck pipe"`</span>, report #39's own hole-drag line</span>
<span id="cb8-410"><a href="#cb8-410" aria-hidden="true" tabindex="-1"></a>scores close behind it, and the genuinely unrelated line trails both by</span>
<span id="cb8-411"><a href="#cb8-411" aria-hidden="true" tabindex="-1"></a>a real margin. A reference solution is in <span class="in">`code/chapter_04/challenge/`</span>.</span>
<span id="cb8-412"><a href="#cb8-412" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-413"><a href="#cb8-413" aria-hidden="true" tabindex="-1"></a><span class="fu">## Key takeaways</span></span>
<span id="cb8-414"><a href="#cb8-414" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-415"><a href="#cb8-415" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Embeddings represent meaning as geometry: similar meaning, nearby</span>
<span id="cb8-416"><a href="#cb8-416" aria-hidden="true" tabindex="-1"></a>  vectors.</span>
<span id="cb8-417"><a href="#cb8-417" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Cosine similarity is the standard comparison because it isolates</span>
<span id="cb8-418"><a href="#cb8-418" aria-hidden="true" tabindex="-1"></a>  direction (meaning) from magnitude.</span>
<span id="cb8-419"><a href="#cb8-419" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Semantic search over whole documents is a real improvement on keyword</span>
<span id="cb8-420"><a href="#cb8-420" aria-hidden="true" tabindex="-1"></a>  search — report #39 goes from unfindable to rank 5 of 10 — but "an</span>
<span id="cb8-421"><a href="#cb8-421" aria-hidden="true" tabindex="-1"></a>  improvement" and "solved" are different claims. Don't oversell it.</span>
<span id="cb8-422"><a href="#cb8-422" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Granularity is often the actual lever, not the embedding model. The</span>
<span id="cb8-423"><a href="#cb8-423" aria-hidden="true" tabindex="-1"></a>  same query, same model, same text — just isolated to individual</span>
<span id="cb8-424"><a href="#cb8-424" aria-hidden="true" tabindex="-1"></a>  narrative lines instead of a whole noisy report — turns a middling</span>
<span id="cb8-425"><a href="#cb8-425" aria-hidden="true" tabindex="-1"></a>  rank-5 result into a clear, checkable win.</span>
<span id="cb8-426"><a href="#cb8-426" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Brute-force cosine search (a matrix multiply) is entirely adequate at</span>
<span id="cb8-427"><a href="#cb8-427" aria-hidden="true" tabindex="-1"></a>  ten documents. It stops being adequate well before you reach the full</span>
<span id="cb8-428"><a href="#cb8-428" aria-hidden="true" tabindex="-1"></a>  76-report archive's scale — that's Chapter 8's problem to solve.</span>
<span id="cb8-429"><a href="#cb8-429" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-430"><a href="#cb8-430" aria-hidden="true" tabindex="-1"></a><span class="fu">## Repository files</span></span>
<span id="cb8-431"><a href="#cb8-431" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-432"><a href="#cb8-432" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> File <span class="pp">|</span> Purpose <span class="pp">|</span></span>
<span id="cb8-433"><a href="#cb8-433" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---|</span></span>
<span id="cb8-434"><a href="#cb8-434" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`code/chapter_04/semantic_search.py`</span> <span class="pp">|</span> Embedding generation and brute-force cosine search <span class="pp">|</span></span>
<span id="cb8-435"><a href="#cb8-435" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`notebooks/chapter_04_explore.ipynb`</span> <span class="pp">|</span> Interactive companion notebook <span class="pp">|</span></span>
<span id="cb8-436"><a href="#cb8-436" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-437"><a href="#cb8-437" aria-hidden="true" tabindex="-1"></a>::: {.callout-caution title="CHECKPOINT — Chapter 4"}</span>
<span id="cb8-438"><a href="#cb8-438" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="va">[x]</span> Explained what a text embedding is without needing the underlying math</span>
<span id="cb8-439"><a href="#cb8-439" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="va">[x]</span> Generated embeddings for a folder of DDR text</span>
<span id="cb8-440"><a href="#cb8-440" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="va">[x]</span> Ranked reports by semantic similarity to a query using cosine similarity</span>
<span id="cb8-441"><a href="#cb8-441" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="va">[x]</span> Diagnosed granularity, not the model, as the real bottleneck</span>
<span id="cb8-442"><a href="#cb8-442" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb8-443"><a href="#cb8-443" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-444"><a href="#cb8-444" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip .built-box title="✓ WHAT YOU BUILT"}</span>
<span id="cb8-445"><a href="#cb8-445" aria-hidden="true" tabindex="-1"></a>**`semantic_search.py`** — a brute-force semantic search engine: embed a</span>
<span id="cb8-446"><a href="#cb8-446" aria-hidden="true" tabindex="-1"></a>folder of reports once, then rank any query against them by meaning, not</span>
<span id="cb8-447"><a href="#cb8-447" aria-hidden="true" tabindex="-1"></a>spelling.</span>
<span id="cb8-448"><a href="#cb8-448" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb8-449"><a href="#cb8-449" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-450"><a href="#cb8-450" aria-hidden="true" tabindex="-1"></a><span class="fu">## What can you do now that you couldn't do before?</span></span>
<span id="cb8-451"><a href="#cb8-451" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-452"><a href="#cb8-452" aria-hidden="true" tabindex="-1"></a>You can retrieve relevant report passages by meaning instead of exact</span>
<span id="cb8-453"><a href="#cb8-453" aria-hidden="true" tabindex="-1"></a>wording — finding report #39's continued-risk language even though it</span>
<span id="cb8-454"><a href="#cb8-454" aria-hidden="true" tabindex="-1"></a>never says "stuck" — and you know precisely why the result isn't perfect</span>
<span id="cb8-455"><a href="#cb8-455" aria-hidden="true" tabindex="-1"></a>yet: granularity, not the model, is the real bottleneck.</span>
<span id="cb8-456"><a href="#cb8-456" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-457"><a href="#cb8-457" aria-hidden="true" tabindex="-1"></a><span class="fu">## Suggested next step</span></span>
<span id="cb8-458"><a href="#cb8-458" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-459"><a href="#cb8-459" aria-hidden="true" tabindex="-1"></a>**Coming up in Chapter 5:** You can now retrieve relevant passages by</span>
<span id="cb8-460"><a href="#cb8-460" aria-hidden="true" tabindex="-1"></a>meaning, and you've learned the honest limits of doing it at</span>
<span id="cb8-461"><a href="#cb8-461" aria-hidden="true" tabindex="-1"></a>whole-document granularity. Chapter 5 turns retrieval into an answer:</span>
<span id="cb8-462"><a href="#cb8-462" aria-hidden="true" tabindex="-1"></a>given a question, retrieve the right evidence, and generate a response</span>
<span id="cb8-463"><a href="#cb8-463" aria-hidden="true" tabindex="-1"></a>that cites exactly where each claim came from. Chapter 7 comes back to</span>
<span id="cb8-464"><a href="#cb8-464" aria-hidden="true" tabindex="-1"></a>fix the granularity problem directly.</span>
</code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Building Industrial RAG Systems from Daily Drilling Reports</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/djimrastephane/ddr-rag-book/edit/main/chapters/chapter_04.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/djimrastephane/ddr-rag-book/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>Built with Quarto</p>
</div>
  </div>
</footer>




</body></html>